"""ICD-10 codes for Vietnamese CHẨN_ĐOÁN. Auto-built from v11r3 (38.99 baseline)."""

ICD10_DICT = {
    "amyloidosis": ["E85.9"],
    "bàng quang thần kinh": ["N31.9"],
    "béo phì": ["E66.9"],
    "bạch biến": ["L80"],
    "bại não": ["G80.9"],
    "bệnh amyloidosis": ["E85.9"],
    "bệnh amyloidosis chuỗi nhẹ": ["E85.8"],
    "bệnh amyloidosis di truyền hoặc gia đình": ["E85.2"],
    "bệnh amyloidosis tự miễn dịch": ["E85.3"],
    "bệnh ba thân động mạch vành nghiêm trọng": ["I25.1"],
    "bệnh bàn chân bẹt": ["Q66.5"],
    "bệnh bạch cầu dòng tủy mãn tính": ["C92.1"],
    "bệnh dại ở người": ["A82.9"],
    "bệnh gan do rượu": ["K70.9"],
    "bệnh gout mạn tính": ["M10.9"],
    "bệnh gút": ["M10.9"],
    "bệnh kawasaki": ["M30.3"],
    "bệnh lý thần kinh ngoại biên": ["G62.9"],
    "bệnh mạch máu ngoại biên": ["I73.9"],
    "bệnh phổi kẽ": ["J84.9"],
    "bệnh phổi tắc nghẽn mạn tính": ["J44.9"],
    "bệnh phổi tắc nghẽn mạn tính, không xác định": ["J44.9"],
    "bệnh thoái hóa tinh bột": ["E85.9"],
    "bệnh thận mạn tính": ["N18.9"],
    "bệnh thận mạn, không đặc hiệu": ["N18.9"],
    "bệnh thận mạn, không đặc hiệu giai đoạn 4": ["N18.4"],
    "bệnh thủy đậu": ["B01.9"],
    "bệnh tim mạch do xơ vữa động mạch": ["I25.1"],
    "bệnh tăng đông máu": ["D68.6"],
    "bệnh vảy nến": ["L40.9"],
    "bệnh đa xơ cứng": ["G35"],
    "bệnh động mạch vành": ["I25.1"],
    "bệnhgout": ["M10.9"],
    "cao răng": ["K03.6"],
    "chậm phát triển trí tuệ": ["F79"],
    "cml": ["C92.1"],
    "cơn tim nhanh nhĩ": ["I47.1"],
    "cơn đau thắt ngực không ổn định": ["I20.0"],
    "dị tật còn ống động mạch": ["Q25.0"],
    "dị tật thiểu sản vành tai": ["Q17.2"],
    "ghép thận thất bại": ["T86.1"],
    "giai đoạn trầm cảm không đặc hiệu": ["F32.9"],
    "giãn phế quản": ["J47"],
    "giãn thừng tinh": ["I86.1"],
    "giả gout": ["M11.2"],
    "gout": ["M10.9"],
    "graves": ["E05.0"],
    "gãy xương": ["T14.2"],
    "hẹp ống sống": ["M48.0"],
    "hội chứng tăng đông": ["D68.6"],
    "hội chứng buồng trứng đa nang": ["E28.2"],
    "hội chứng bàn chân bẹt bẩm sinh": ["Q66.5"],
    "hội chứng ruột kích thích": ["K58"],
    "hội chứng thận hư": ["N04.9"],
    "hội chứng turner": ["Q96.9"],
    "kawasaki": ["M30.3"],
    "loãng xương": ["M81.9"],
    "loét thực quản": ["K22.1"],
    "loét tá tràng": ["K26.9"],
    "loét tì đè giai đoạn iv mãn tính": ["L89.9"],
    "mày đay mạn": ["L50.8"],
    "mày đay mạn tính": ["L50.8"],
    "mày đay vô căn": ["L50.1"],
    "mụn trứng cá": ["L70.9"],
    "ngoại tâm thu nhĩ": ["I49.1"],
    "ngoại tâm thu thất": ["I49.3"],
    "ngưng thở khi ngủ": ["G47.3"],
    "ngưng thở khi ngủ do tắc nghẽn": ["G47.3"],
    "ngừng thở khi ngủ": ["G47.3"],
    "nhiễm khuẩn huyết": ["A41.0"],
    "nhiễm khuẩn tiết niệu": ["N39.0"],
    "nhiễm khuẩn đường tiêu hóa": ["A09"],
    "nhiễm khuẩn đường tiết niệu": ["N39.0"],
    "nhiễm khuẩn đường tiết niệu, vị trí không xác định": ["N39.0"],
    "nhiễm trùng huyết": ["A41.9"],
    "nhiễm trùng đường tiết niệu": ["N39.0"],
    "nhịp nhanh": ["R00.0"],
    "nhịp nhanh trên thất": ["I47.1"],
    "nhồi máu cơ tim": ["I21.9"],
    "não úng thuỷ khác": ["G91.8"],
    "não úng thủy": ["G91.9"],
    "não úng tuỷ": ["G91.9"],
    "nấm bẹn": ["B35.6"],
    "parkinson": ["G20"],
    "phình giãn động mạch vành": ["I25.4"],
    "phù gai thị": ["H47.1"],
    "phù phổi cấp": ["J81"],
    "rung nhĩ": ["I48.9"],
    "rối loạn chuyển hóa tinh bột": ["E85.9"],
    "rối loạn cảm xúc": ["F39"],
    "rối loạn cảm xúc lưỡng cực khác": ["F31.8"],
    "rối loạn lipid máu": ["E78.5"],
    "rối loạn lo âu": ["F41.9"],
    "rối loạn lưỡng cực": ["F31.9"],
    "rụng tóc toàn bộ": ["L63.1"],
    "rụng tóc toàn thể": ["L63.1"],
    "rụng tóc từng mảng": ["L63.9"],
    "rụng tóc từng vùng": ["L63.9"],
    "suy giảm miễn dịch": ["D84.9"],
    "suy thận": ["N19"],
    "suy thận cấp": ["N17.9"],
    "suy thận mạn": ["N18.9"],
    "suy thận mạn giai đoạn v": ["N18.5"],
    "suy tim": ["I50.9"],
    "sâu răng": ["K02.9"],
    "sỏi mật": ["K80.2"],
    "sỏi niệu quản": ["N20.1"],
    "sỏi thận": ["N20.0"],
    "tai biến mạch máu não": ["I64"],
    "tan huyết": ["D58.9"],
    "thai ngoài tử cung": ["O00.9"],
    "thiếu men g6pd": ["D55.0"],
    "thiếu máu": ["D50.9"],
    "thiếu máu cơ tim": ["I25.9"],
    "thiếu máu cơ tim cục bộ": ["I25.9"],
    "thiếu máu tan huyết": ["D58.9"],
    "thrombophilia": ["D68.6"],
    "thuyên tắc phổi": ["I26.9"],
    "tim to": ["I51.7"],
    "tiền sản giật": ["O14.9"],
    "tiền sản giật": ["O14.9"],
    "tiểu đường": ["E11.9"],
    "tràn dịch màng ngoài tim": ["I31.3"],
    "tràn dịch màng phổi": ["J90"],
    "trào ngược dạ dày thực quản": ["K21.9"],
    "trầm cảm": ["F32.9"],
    "trứng cá": ["L70.9"],
    "tàn nhang": ["L81.2"],
    "tâm phế mạn": ["I27.9"],
    "tăng cholesterol máu đơn thuần": ["E78.0"],
    "tăng huyết áp": ["I10"],
    "tăng kali máu": ["E87.5"],
    "tăng lipid máu": ["E78.5"],
    "tăng lipid máu, không đặc hiệu": ["E78.5"],
    "tăng sản tuyến bã nhờn": ["L73.8"],
    "tăng sản tuyến tiền liệt": ["N40"],
    "tăng áp lực tĩnh mạch cửa": ["K76.6"],
    "tịt ống tai ngoài bẩm sinh": ["Q16.1"],
    "u dây thần kinh số viii": ["D33.3"],
    "u nang tuyến vú": ["N60.9"],
    "u xơ tuyến vú": ["N60.2"],
    "u ác của tuyến tiền liệt": ["C61"],
    "ung thư biểu mô tế bào vảy xâm nhập của dương vật": ["C60.9"],
    "ung thư cổ tử cung": ["C53.9"],
    "ung thư tuyến giáp": ["C73"],
    "ung thư vú": ["C50.9"],
    "ung thư đại tràng": ["C18.9"],
    "viêm bao tử": ["K29.7"],
    "viêm bể thận": ["N12"],
    "viêm cơ tim": ["I51.4"],
    "viêm cầu thận": ["N05.9"],
    "viêm cầu thận mạn": ["N03.9"],
    "viêm da tiếp xúc": ["L25.9"],
    "viêm da tiếp xúc dị ứng": ["L23.9"],
    "viêm dạ dày": ["K29.7"],
    "viêm dạ dày ruột do virus": ["A08.4"],
    "viêm gan": ["K75.9"],
    "viêm gan b": ["B18.1"],
    "viêm gan cấp tính do virus b thể thông thường điển hình mức độ nặng giai đoạn toàn phát": ["B16.9"],
    "viêm hang vị sung huyết": ["K29.7"],
    "viêm họng": ["J02.9"],
    "viêm khớp dạng thấp": ["M06.9"],
    "viêm kết mạc": ["H10.9"],
    "viêm loét đại tràng": ["K51.9"],
    "viêm mô tế bào": ["L03.9"],
    "viêm mạch máu": ["I77.6"],
    "viêm nha chu": ["K05.6"],
    "viêm phế quản": ["J40"],
    "viêm phổi": ["J18.9"],
    "viêm phổi bệnh viện": ["J18.9"],
    "viêm phổi hoại tử": ["J85.0"],
    "viêm phổi kẽ": ["J84.9"],
    "viêm quanh răng": ["K05.6"],
    "viêm sung huyết hang vị dạ dày": ["K29.7"],
    "viêm thực quản": ["K20"],
    "viêm tim": ["I51.4"],
    "viêm túi mật": ["K81.0", "K81.9"],
    "viêm tủy xương": ["M86.9"],
    "viêm xương tủy": ["M86.9"],
    "vpht": ["J85.0"],
    "xhth": ["K92.2"],
    "xuất huyết dưới nhện": ["I60.9"],
    "xuất huyết tiêu hóa": ["K92.2"],
    "xơ gan": ["K74.6"],
    "xơ gan do rượu": ["K70.3"],
    "xơ vữa động mạch": ["I70.9"],
    "xẹp phổi": ["J98.1"],
    "áp xe phổi": ["J85.1"],
    "áp-xe phổi": ["J85.1"],
    "đa u tủy": ["C90.0"],
    "đái tháo đường": ["E11.9"],
    "đột quỵ": ["I64"],
    "đột tử": ["R96.0"],
    "đợt cấp copd": ["J44.1"],
    "ổ loét trong bao tử": ["K25.9"],
}

# Sorted by length (longest first) for longest-match-first search
ICD10_KEYS_SORTED = sorted(ICD10_DICT.keys(), key=lambda x: -len(x))
