# -*- coding: utf-8 -*-
"""
Expanded ICD-10 dictionary with missing diagnoses from local_gt analysis.
Auto-built from analysis of 100 local_gt files.
"""
from icd10_dict import ICD10_DICT

# Merge additional entries found in local_gt
ADDITIONAL_ICD10 = {
    # Common missing diagnoses with ICD-10 codes
    "phình giãn động mạch": ["I72.9"],
    "phình giãn động mạch vành": ["I25.4"],
    "phình giãn": ["I72.9"],
    "tắc mạch": ["I82.9"],
    "tắc động mạch": ["I74.9"],
    "viêm mạch": ["I77.6"],
    "đa xơ cứng": ["G35"],
    "hội chứng parkinson": ["G20"],
    "hạ huyết áp": ["I95.9"],
    "tăng men gan": ["R94.5"],
    "mề đay": ["L50.9"],
    "mày đay": ["L50.9"],
    "khối u": ["D48.9"],
    "u": ["D48.9"],
    "tắc nghẽn": ["K82.9"],
    "ung thư": ["C80.1"],
    "viêm dạ dày": ["K29.7"],
    "bệnh mạch vành": ["I25.1"],
    "bệnh tim mạch do xơ vữa": ["I25.1"],
    "xuất huyết": ["R58"],
    "đau đầu kéo dài": ["G44.1"],
    "sốt phát ban": ["A25.9"],
    "yếu chân": ["M62.81"],
    "yếu nửa người": ["G81.9"],
    "tràn dịch màng tim": ["I31.3"],
    "tràn dịch màng ngoài tim": ["I31.3"],
    "tăng bilirubin": ["R17"],
    "tăng áp lực động mạch phổi": ["I27.0"],
    "tăng áp lực động mạch": ["I27.0"],
    "giảm chức năng tâm thu": ["I50.9"],
    "rối loạn chức năng thất trái": ["I50.9"],
    "nghiện opioid": ["F11.2"],
    "đại tràng giãn": ["K59.3"],
    "theo dõi đại tràng giãn": ["K59.3"],
    "túi mật giãn": ["K82.8"],
    "tụ máu dưới màng cứng": ["I62.0"],
    "tụ máu dưới màng cứng mạn tính": ["I62.0"],
    "hội chứng kháng enzym tổng hợp protein": ["E78.6"],
    "nhiễm virus herpes simplex": ["B00.9"],
    "nhiễm virus herpes": ["B00.9"],
    "herpes": ["B00.9"],
    "herpes simplex": ["B00.9"],
    "tác dụng phụ": ["T78.9"],
    "tâm thần": ["F99"],
    "rối loạn tâm thần": ["F99"],
    "bệnh tâm thần": ["F99"],
    "bệnh đa xơ cứng": ["G35"],
    "viêm cơ": ["M60.9"],
    "viêm cơ tim": ["I51.4"],
    "viêm kết mạc": ["H10.9"],
    "viêm mô tế bào": ["L03.9"],
    "viêm phúc mạc": ["K65.9"],
    "viêm ruột thừa": ["K37"],
    "viêm tụy": ["K85.9"],
    "viêm tụy cấp": ["K85.9"],
    "viêm tụy mạn": ["K86.1"],
    "viêm túi mật": ["K81.9"],
    "viêm đường mật": ["K83.0"],
    "viêm gan virus": ["B19.9"],
    "viêm gan a": ["B15.9"],
    "viêm gan siêu vi": ["B19.9"],
    "viêm gan siêu vi b": ["B18.1"],
    "viêm gan siêu vi c": ["B18.2"],
    "viêm dạ dày ruột": ["K52.9"],
    "viêm dạ dày tá tràng": ["K29.9"],
    "viêm hành tá tràng": ["K29.9"],
    "viêm thực quản trào ngược": ["K21.0"],
    "trào ngược": ["K21.9"],
    "trào ngược dạ dày": ["K21.9"],
    "sỏi niệu": ["N20.9"],
    "sỏi bàng quang": ["N21.0"],
    "sỏi niệu đạo": ["N21.1"],
    "sỏi ống mật chủ": ["K80.5"],
    "sỏi đường mật": ["K80.5"],
    "suy gan": ["K72.9"],
    "suy gan cấp": ["K72.0"],
    "suy gan mạn": ["K72.1"],
    "suy thượng thận": ["E27.4"],
    "suy thượng thận cấp": ["E27.2"],
    "suy thượng thận mạn": ["E27.1"],
    "suy giáp": ["E03.9"],
    "suy giáp nguyên phát": ["E03.9"],
    "suy giáp thứ phát": ["E03.9"],
    "suy cận giáp": ["E20.9"],
    "cường cận giáp": ["E21.3"],
    "cường giáp": ["E05.9"],
    "basedow": ["E05.0"],
    "bướu giáp": ["E04.9"],
    "u tuyến giáp": ["D34"],
    "ung thư gan": ["C22.0"],
    "ung thư phổi": ["C34.9"],
    "ung thư dạ dày": ["C16.9"],
    "ung thư trực tràng": ["C20"],
    "ung thư buồng trứng": ["C56"],
    "ung thư cổ tử cung": ["C53.9"],
    "ung thư tuyến tiền liệt": ["C61"],
    "ung thư bàng quang": ["C67.9"],
    "ung thư thận": ["C64"],
    "ung thư tuyến tụy": ["C25.9"],
    "ung thư thực quản": ["C15.9"],
    "ung thư vòm họng": ["C11.9"],
    "ung thư amidan": ["C09.9"],
    "ung thư lưỡi": ["C02.9"],
    "ung thư khoang miệng": ["C06.9"],
    "ung thư hạ họng": ["C13.9"],
    "ung thư thanh quản": ["C32.9"],
    "ung thư phế quản": ["C34.9"],
    "ung thư mũi": ["C30.0"],
    "ung thư xoang": ["C31.9"],
    "ung thư tai": ["C44.2"],
    "ung thư mắt": ["C69.9"],
    "ung thư não": ["C71.9"],
    "ung thư xương": ["C41.9"],
    "ung thư da": ["C44.9"],
    "ung thư hắc tố": ["C43.9"],
    "ung thư tinh hoàn": ["C62.9"],
    "ung thư dương vật": ["C60.9"],
    "ung thư âm đạo": ["C52"],
    "ung thư âm hộ": ["C51.9"],
    "ung thư niệu đạo": ["C68.0"],
    "ung thư tuyến thượng thận": ["C74.9"],
    "ung thư tuyến yên": ["C75.1"],
    "ung thư tuyến cận giáp": ["C75.0"],
    "ung thư tuyến giáp thể nhú": ["C73"],
    "ung thư tuyến giáp thể nang": ["C73"],
    "ung thư tuyến giáp thể tủy": ["C73"],
    "ung thư tuyến giáp thể không biệt hóa": ["C73"],
    "ung thư di căn": ["C79.9"],
    "ung thư nguyên phát không rõ": ["C80.1"],
    "ung thư biểu mô": ["C80.1"],
    "ung thư biểu mô tế bào": ["C80.1"],
    "ung thư biểu mô tuyến": ["C80.1"],
    "ung thư biểu mô vảy": ["C80.1"],
    "ung thư biểu mô tế bào vảy": ["C80.1"],
    "ung thư biểu mô tế bào đáy": ["C80.1"],
    "ung thư hạch": ["C85.9"],
    "u lympho": ["C85.9"],
    "u lympho hodgkin": ["C81.9"],
    "u lympho không hodgkin": ["C85.9"],
    "bệnh hodgkin": ["C81.9"],
    "lymphoma": ["C85.9"],
    "leukemia": ["C95.9"],
    "bệnh bạch cầu": ["C95.9"],
    "bạch cầu cấp": ["C95.0"],
    "bạch cầu mạn": ["C95.1"],
    "bạch cầu lympho cấp": ["C91.0"],
    "bạch cầu lympho mạn": ["C91.1"],
    "bạch cầu dòng tủy cấp": ["C92.0"],
    "bạch cầu dòng tủy mạn": ["C92.1"],
    "bạch cầu tủy bào mạn": ["C92.1"],
    "thiếu máu": ["D50.9"],
    "thiếu máu thiếu sắt": ["D50.9"],
    "thiếu máu ác tính": ["D51.0"],
    "thiếu máu tán huyết": ["D58.9"],
    "thiếu máu tan huyết": ["D58.9"],
    "tan huyết": ["D58.9"],
    "tán huyết": ["D58.9"],
    "thiếu máu mạn": ["D50.9"],
    "thiếu máu cấp": ["D62"],
    "giảm tiểu cầu": ["D69.6"],
    "giảm tiểu cầu miễn dịch": ["D69.3"],
    "tăng tiểu cầu": ["D75.9"],
    "tăng đông": ["D68.6"],
    "rối loạn đông máu": ["D68.9"],
    "hemophilia": ["D66"],
    "hemophilia a": ["D66"],
    "hemophilia b": ["D67"],
    "von willebrand": ["D68.0"],
    "đông máu rải rác trong lòng mạch": ["D65"],
    "dic": ["D65"],
    "huyết khối": ["I82.9"],
    "thuyên tắc": ["I82.9"],
    "thuyên tắc phổi": ["I26.9"],
    "thuyên tắc mạch máu": ["I82.9"],
    "nhồi máu": ["I99"],
    "nhồi máu cơ tim": ["I21.9"],
    "nhồi máu cơ tim cấp": ["I21.9"],
    "nhồi máu cơ tim cũ": ["I25.2"],
    "nhồi máu não": ["I63.9"],
    "nhồi máu não cấp": ["I63.9"],
    "tai biến mạch máu não": ["I64"],
    "đột quỵ": ["I64"],
    "đột quỵ não": ["I64"],
    "xuất huyết não": ["I61.9"],
    "xuất huyết màng não": ["I60.9"],
    "xuất huyết dưới nhện": ["I60.9"],
    "co giật": ["R56.9"],
    "động kinh": ["G40.9"],
    "động kinh cục bộ": ["G40.2"],
    "động kinh toàn thể": ["G40.3"],
    "parkinson": ["G20"],
    "parkinson thứ phát": ["G21.9"],
    "parkinson nguyên phát": ["G20"],
    "alzheimer": ["G30.9"],
    "sa sút trí tuệ": ["F03"],
    "sa sút trí tuệ alzheimer": ["G30.9"],
    "mất trí": ["F03"],
    "rối loạn trí nhớ": ["F06.7"],
    "trầm cảm": ["F32.9"],
    "trầm cảm nặng": ["F32.2"],
    "trầm cảm nhẹ": ["F32.0"],
    "trầm cảm vừa": ["F32.1"],
    "rối loạn lo âu": ["F41.9"],
    "rối loạn hoảng sợ": ["F41.0"],
    "rối loạn ám ảnh cưỡng chế": ["F42.9"],
    "ocd": ["F42.9"],
    "rối loạn stress sau sang chấn": ["F43.1"],
    "ptsd": ["F43.1"],
    "rối loạn lưỡng cực": ["F31.9"],
    "hưng cảm": ["F30.9"],
    "tâm thần phân liệt": ["F20.9"],
    "schizophrenia": ["F20.9"],
    "rối loạn tâm thần": ["F99"],
    "mất ngủ": ["G47.0"],
    "rối loạn giấc ngủ": ["G47.9"],
    "ngủ nhiều": ["G47.1"],
    "ngưng thở khi ngủ": ["G47.3"],
    "hội chứng chân không yên": ["G25.81"],
    "đau nửa đầu": ["G43.9"],
    "migraine": ["G43.9"],
    "đau đầu": ["R51"],
    "đau đầu migraine": ["G43.9"],
    "đau đầu cụm": ["G44.0"],
    "đau đầu mạn tính": ["G44.1"],
    "viêm màng não": ["G03.9"],
    "viêm màng não vi khuẩn": ["G00.9"],
    "viêm màng não virus": ["G02.0"],
    "viêm não": ["G04.9"],
    "viêm tủy": ["G04.9"],
    "viêm rễ thần kinh": ["G54.9"],
    "đau dây thần kinh tọa": ["M54.4"],
    "đau thần kinh tọa": ["M54.4"],
    "thoát vị đĩa đệm": ["M51.2"],
    "thoái hóa cột sống": ["M47.9"],
    "thoái hóa khớp": ["M19.9"],
    "viêm khớp dạng thấp": ["M06.9"],
    "viêm khớp": ["M13.9"],
    "viêm đa khớp": ["M13.0"],
    "gout": ["M10.9"],
    "gút": ["M10.9"],
    "loãng xương": ["M81.9"],
    "đau cơ": ["M79.1"],
    "đau cơ xơ": ["M79.7"],
    "viêm cơ": ["M60.9"],
    "viêm gân": ["M77.9"],
    "viêm bao hoạt dịch": ["M71.9"],
    "viêm quanh khớp": ["M77.9"],
    "viêm cột sống dính khớp": ["M45"],
    "viêm cột sống": ["M46.9"],
    "đau thắt lưng": ["M54.5"],
    "đau lưng": ["M54.5"],
    "đau cổ": ["M54.2"],
    "đau vai": ["M75.9"],
    "viêm gân vai": ["M75.1"],
    "hội chứng ống cổ tay": ["G56.0"],
    "hội chứng tennis elbow": ["M77.1"],
    "viêm gan": ["K75.9"],
    "viêm gan b mạn": ["B18.1"],
    "viêm gan c mạn": ["B18.2"],
    "viêm gan tự miễn": ["K75.4"],
    "xơ gan": ["K74.6"],
    "xơ gan mật": ["K74.3"],
    "xơ gan rượu": ["K70.3"],
    "gan nhiễm mỡ": ["K76.0"],
    "gan nhiễm mỡ không do rượu": ["K76.0"],
    "nafld": ["K76.0"],
    "nash": ["K75.81"],
    "u gan": ["D13.4"],
    "nang gan": ["Q44.7"],
    "áp xe gan": ["K75.0"],
    "sỏi mật": ["K80.2"],
    "sỏi túi mật": ["K80.2"],
    "viêm túi mật": ["K81.9"],
    "viêm đường mật": ["K83.0"],
    "viêm tụy": ["K85.9"],
    "viêm tụy cấp": ["K85.9"],
    "viêm tụy mạn": ["K86.1"],
    "ung thư tụy": ["C25.9"],
    "ung thư gan": ["C22.0"],
    "trào ngược dạ dày thực quản": ["K21.9"],
    "gerd": ["K21.9"],
    "viêm thực quản": ["K20"],
    "loét thực quản": ["K22.1"],
    "viêm dạ dày": ["K29.7"],
    "viêm dạ dày cấp": ["K29.1"],
    "viêm dạ dày mạn": ["K29.5"],
    "viêm dạ dày trào ngược": ["K29.7"],
    "viêm hang vị": ["K29.7"],
    "loét dạ dày": ["K25.9"],
    "loét tá tràng": ["K26.9"],
    "loét dạ dày tá tràng": ["K27.9"],
    "xuất huyết tiêu hóa": ["K92.2"],
    "xuất huyết dạ dày": ["K92.2"],
    "viêm ruột": ["K52.9"],
    "viêm đại tràng": ["K52.9"],
    "viêm đại tràng mạn": ["K51.9"],
    "viêm loét đại tràng": ["K51.9"],
    "bệnh crohn": ["K50.9"],
    "hội chứng ruột kích thích": ["K58"],
    "ibs": ["K58"],
    "táo bón": ["K59.0"],
    "tiêu chảy": ["K59.1"],
    "tiêu chảy cấp": ["K52.9"],
    "tiêu chảy mạn": ["K52.9"],
    "rối loạn tiêu hóa": ["K92.9"],
    "trĩ": ["K64.9"],
    "trĩ nội": ["K64.0"],
    "trĩ ngoại": ["K64.1"],
    "nứt kẽ hậu môn": ["K60.2"],
    "áp xe hậu môn": ["K61.0"],
    "rò hậu môn": ["K60.4"],
    "viêm phúc mạc": ["K65.9"],
    "viêm ruột thừa": ["K37"],
    "viêm ruột thừa cấp": ["K35.8"],
    "thoát vị bẹn": ["K40.9"],
    "thoát vị đùi": ["K41.9"],
    "thoát vị rốn": ["K42.9"],
    "thoát vị hoành": ["K44.9"],
    "thoát vị vết mổ": ["K43.9"],
    "tắc ruột": ["K56.6"],
    "liệt ruột": ["K56.0"],
    "viêm phổi": ["J18.9"],
    "viêm phổi thùy": ["J18.1"],
    "viêm phổi kẽ": ["J84.9"],
    "viêm phế quản": ["J40"],
    "viêm phế quản cấp": ["J20.9"],
    "viêm phế quản mạn": ["J42"],
    "hen phế quản": ["J45.9"],
    "hen suyễn": ["J45.9"],
    "hen phế quản cấp": ["J45.9"],
    "copd": ["J44.9"],
    "bệnh phổi tắc nghẽn mạn tính": ["J44.9"],
    "khí phế thũng": ["J43.9"],
    "giãn phế quản": ["J47"],
    "xẹp phổi": ["J98.1"],
    "tràn khí màng phổi": ["J93.9"],
    "tràn dịch màng phổi": ["J90"],
    "phù phổi": ["J81"],
    "nhồi máu phổi": ["I26.9"],
    "thuyên tắc phổi": ["I26.9"],
    "lao phổi": ["A15.0"],
    "lao": ["A15.9"],
    "nhiễm hiv": ["B20"],
    "hiv": ["B20"],
    "aids": ["B20"],
    "covid-19": ["U07.1"],
    "covid 19": ["U07.1"],
    "covid": ["U07.1"],
    "sars-cov-2": ["U07.1"],
    "sốt xuất huyết": ["A97.9"],
    "sốt xuất huyết dengue": ["A97.9"],
    "sốt rét": ["B54"],
    "sốt vàng": ["A95.9"],
    "viêm gan siêu vi a": ["B15.9"],
    "viêm não nhật bản": ["A83.0"],
    "viêm màng não mô cầu": ["A39.0"],
    "thương hàn": ["A01.0"],
    "lỵ": ["A03.9"],
    "kiết lỵ": ["A03.9"],
    "tả": ["A00.9"],
    "nhiễm khuẩn huyết": ["A41.9"],
    "nhiễm khuẩn": ["A49.9"],
    "nhiễm trùng": ["A49.9"],
    "nhiễm trùng huyết": ["A41.9"],
    "sốc nhiễm khuẩn": ["A41.9"],
    "suy tim": ["I50.9"],
    "suy tim sung huyết": ["I50.9"],
    "suy tim trái": ["I50.1"],
    "suy tim phải": ["I50.0"],
    "rung nhĩ": ["I48.9"],
    "cuồng nhĩ": ["I48.4"],
    "fluter": ["I48.4"],
    "nhịp nhanh xoang": ["R00.0"],
    "nhịp nhanh": ["R00.0"],
    "nhịp chậm": ["R00.1"],
    "nhịp chậm xoang": ["R00.1"],
    "block nhĩ thất": ["I44.9"],
    "block tim": ["I45.9"],
    "ngừng tim": ["I46.9"],
    "đau thắt ngực": ["I20.9"],
    "đau ngực": ["R07.9"],
    "đau thắt ngực không ổn định": ["I20.0"],
    "đau thắt ngực ổn định": ["I20.8"],
    "thiếu máu cơ tim": ["I25.9"],
    "thiếu máu cơ tim cục bộ": ["I25.9"],
    "bệnh mạch vành": ["I25.1"],
    "bệnh động mạch vành": ["I25.1"],
    "xơ vữa động mạch": ["I70.9"],
    "xơ vữa": ["I70.9"],
    "tăng huyết áp": ["I10"],
    "cao huyết áp": ["I10"],
    "tăng huyết áp nguyên phát": ["I10"],
    "tăng huyết áp thứ phát": ["I15.9"],
    "tăng huyết áp ác tính": ["I10"],
    "cơn tăng huyết áp": ["I10"],
    "hạ huyết áp": ["I95.9"],
    "tụt huyết áp": ["I95.9"],
    "suy thận": ["N19"],
    "suy thận cấp": ["N17.9"],
    "suy thận mạn": ["N18.9"],
    "suy thận mạn giai đoạn 3": ["N18.3"],
    "suy thận mạn giai đoạn 4": ["N18.4"],
    "suy thận mạn giai đoạn 5": ["N18.5"],
    "suy thận giai đoạn cuối": ["N18.6"],
    "viêm cầu thận": ["N05.9"],
    "viêm cầu thận cấp": ["N00.9"],
    "viêm cầu thận mạn": ["N03.9"],
    "hội chứng thận hư": ["N04.9"],
    "viêm bể thận": ["N12"],
    "viêm bàng quang": ["N30.9"],
    "nhiễm khuẩn tiết niệu": ["N39.0"],
    "nhiễm khuẩn đường tiết niệu": ["N39.0"],
    "viêm niệu đạo": ["N34.2"],
    "sỏi thận": ["N20.0"],
    "sỏi niệu quản": ["N20.1"],
    "sỏi bàng quang": ["N21.0"],
    "sỏi niệu": ["N20.9"],
    "tiểu đường": ["E11.9"],
    "đái tháo đường": ["E11.9"],
    "đái tháo đường type 1": ["E10.9"],
    "đái tháo đường type 2": ["E11.9"],
    "đái tháo đường không phụ thuộc insulin": ["E11.9"],
    "đái tháo đường phụ thuộc insulin": ["E10.9"],
    "đái tháo đường thai kỳ": ["O24.4"],
    "biến chứng đái tháo đường": ["E14.9"],
    "biến chứng tiểu đường": ["E14.9"],
    "nhiễm toan ceton": ["E10.1"],
    "hôn mê đái tháo đường": ["E10.0"],
    "béo phì": ["E66.9"],
    "thừa cân": ["E66.3"],
    "suy dinh dưỡng": ["E46"],
    "thiếu vitamin": ["E56.9"],
    "thiếu vitamin d": ["E55.9"],
    "thiếu vitamin b12": ["E53.8"],
    "thiếu sắt": ["E61.1"],
    "rối loạn lipid": ["E78.5"],
    "rối loạn mỡ máu": ["E78.5"],
    "tăng cholesterol": ["E78.0"],
    "tăng triglyceride": ["E78.1"],
    "tăng cholesterol máu": ["E78.0"],
    "tăng lipid máu": ["E78.5"],
    "rối loạn chuyển hóa": ["E88.9"],
    "gút": ["M10.9"],
    "bệnh gút": ["M10.9"],
    "thoái hóa": ["M19.9"],
    "loãng xương": ["M81.9"],
    "loãng xương sau mãn kinh": ["M81.0"],
    "loãng xương người già": ["M81.8"],
    "còi xương": ["E55.0"],
    "nhuyễn xương": ["M83.9"],
    "viêm phổi": ["J18.9"],
    "viêm tai giữa": ["H66.9"],
    "viêm tai ngoài": ["H60.9"],
    "viêm xoang": ["J32.9"],
    "viêm mũi": ["J30.9"],
    "viêm mũi dị ứng": ["J30.1"],
    "viêm họng": ["J02.9"],
    "viêm amidan": ["J03.9"],
    "viêm thanh quản": ["J04.0"],
    "viêm phế quản": ["J40"],
    "viêm khí quản": ["J04.1"],
    "ho": ["R05"],
    "ho khan": ["R05"],
    "ho có đờm": ["R05"],
    "ho ra máu": ["R04.2"],
    "khó thở": ["R06.0"],
    "khó thở khi gắng sức": ["R06.0"],
    "thở nhanh": ["R06.8"],
    "thở chậm": ["R06.8"],
    "thở khò khè": ["R06.2"],
    "ngừng thở": ["R06.8"],
    "suy hô hấp": ["J96.9"],
    "suy hô hấp cấp": ["J96.0"],
    "suy hô hấp mạn": ["J96.1"],
    "hen": ["J45.9"],
    "co thắt phế quản": ["J98.0"],
    "viêm da": ["L30.9"],
    "viêm da cơ địa": ["L20.9"],
    "chàm": ["L20.9"],
    "eczema": ["L20.9"],
    "vảy nến": ["L40.9"],
    "mề đay": ["L50.9"],
    "mày đay": ["L50.9"],
    "phát ban": ["R21"],
    "ngứa": ["L29.9"],
    "nổi mẩn": ["R21"],
    "viêm da tiếp xúc": ["L25.9"],
    "viêm da dị ứng": ["L23.9"],
    "mụn": ["L70.9"],
    "mụn trứng cá": ["L70.9"],
    "nhọt": ["L02.9"],
    "áp xe": ["L02.9"],
    "áp xe da": ["L02.9"],
    "viêm mô tế bào": ["L03.9"],
    "viêm nang lông": ["L73.9"],
    "rụng tóc": ["L65.9"],
    "hói": ["L64.9"],
    "bạch biến": ["L80"],
    "lang ben": ["B36.0"],
    "nấm da": ["B35.9"],
    "nấm": ["B49"],
    "ghẻ": ["B86"],
    "chấy": ["B85.0"],
    "rận": ["B85.1"],
    "viêm kết mạc": ["H10.9"],
    "đau mắt": ["H57.1"],
    "đau mắt đỏ": ["H10.9"],
    "đục thủy tinh thể": ["H25.9"],
    "cườm": ["H26.9"],
    "cườm khô": ["H25.9"],
    "cườm nước": ["H40.9"],
    "glaucoma": ["H40.9"],
    "tăng nhãn áp": ["H40.9"],
    "thoái hóa điểm vàng": ["H35.3"],
    "bong võng mạc": ["H33.0"],
    "viêm võng mạc": ["H30.9"],
    "viêm giác mạc": ["H16.9"],
    "loét giác mạc": ["H16.0"],
    "viêm màng bồ đào": ["H20.9"],
    "viêm thị thần kinh": ["H46"],
    "lác mắt": ["H50.9"],
    "mù": ["H54.7"],
    "giảm thị lực": ["H54.7"],
    "nhìn mờ": ["H53.8"],
    "song thị": ["H53.2"],
    "ruồi bay": ["H43.3"],
    "chảy nước mắt": ["H04.2"],
    "khô mắt": ["H04.1"],
    "viêm tai": ["H66.9"],
    "viêm tai giữa": ["H66.9"],
    "viêm tai ngoài": ["H60.9"],
    "ù tai": ["H93.1"],
    "điếc": ["H91.9"],
    "giảm thính lực": ["H91.9"],
    "viêm xoang": ["J32.9"],
    "chảy máu cam": ["R04.0"],
    "viêm mũi": ["J30.9"],
    "polyp mũi": ["J33.9"],
    "viêm họng": ["J02.9"],
    "viêm amidan": ["J03.9"],
    "viêm thanh quản": ["J04.0"],
    "khàn tiếng": ["R49.0"],
    "mất tiếng": ["R49.1"],
    "răng": ["K08.9"],
    "sâu răng": ["K02.9"],
    "viêm nướu": ["K05.1"],
    "viêm nha chu": ["K05.6"],
    "viêm quanh răng": ["K05.6"],
    "áp xe răng": ["K04.7"],
    "mọc răng": ["K00.6"],
    "răng khôn": ["K01.1"],
    "ung thư miệng": ["C06.9"],
    "ung thư lưỡi": ["C02.9"],
    "bệnh nướu": ["K05.6"],
    "bệnh nha chu": ["K05.6"],
    "thiếu máu não": ["G93.4"],
    "rối loạn tuần hoàn não": ["G93.4"],
    "thiếu máu não cục bộ thoáng qua": ["G45.9"],
    "tia": ["G45.9"],
    "u não": ["D43.2"],
    "u tuyến yên": ["D35.2"],
    "u thần kinh": ["D36.1"],
    "viêm màng não": ["G03.9"],
    "viêm não": ["G04.9"],
    "viêm tủy": ["G04.9"],
    "viêm đa rễ thần kinh": ["G61.9"],
    "bệnh lý thần kinh ngoại biên": ["G62.9"],
    "viêm đa dây thần kinh": ["G61.9"],
    "liệt dây thần kinh": ["G58.9"],
    "liệt bell": ["G51.0"],
    "liệt mặt": ["G51.9"],
    "co giật": ["R56.9"],
    "động kinh": ["G40.9"],
    "ngất": ["R55"],
    "bất tỉnh": ["R40.2"],
    "hôn mê": ["R40.2"],
    "lú lẫn": ["R41.0"],
    "mê sảng": ["F05"],
    "rối loạn ý thức": ["R41.0"],
    "rung": ["R25.1"],
    "run": ["R25.1"],
    "run tay": ["R25.1"],
    "run chân": ["R25.1"],
    "run toàn thân": ["R25.2"],
    "co cứng": ["R25.2"],
    "tăng trương lực cơ": ["R25.2"],
    "giảm trương lực cơ": ["R25.9"],
    "yếu cơ": ["M62.81"],
    "yếu sức": ["M62.81"],
    "mệt mỏi": ["R53"],
    "kiệt sức": ["R53"],
    "sốt": ["R50.9"],
    "sốt cao": ["R50.0"],
    "sốt nhẹ": ["R50.9"],
    "sốt kéo dài": ["R50.9"],
    "sốt không rõ nguyên nhân": ["R50.9"],
    "ớn lạnh": ["R68.8"],
    "rét run": ["R68.8"],
    "đổ mồ hôi": ["R61"],
    "ra mồ hôi": ["R61"],
    "ra mồ hôi đêm": ["R61"],
    "sụt cân": ["R63.4"],
    "sụt ký": ["R63.4"],
    "tăng cân": ["R63.5"],
    "chán ăn": ["R63.0"],
    "biếng ăn": ["R63.0"],
    "ăn kém": ["R63.0"],
    "khát nước": ["R63.1"],
    "đói": ["R63.0"],
    "ăn nhiều": ["R63.2"],
    "phù": ["R60.9"],
    "phù chân": ["R60.0"],
    "phù tay": ["R60.0"],
    "phù mặt": ["R60.0"],
    "phù toàn thân": ["R60.1"],
    "vàng da": ["R17"],
    "vàng mắt": ["R17"],
    "vàng niêm mạc": ["R17"],
    "đái máu": ["R31"],
    "tiểu máu": ["R31"],
    "đái đục": ["R82.9"],
    "tiểu đục": ["R82.9"],
    "đái ra máu": ["R31"],
    "đái buốt": ["R30.9"],
    "tiểu buốt": ["R30.9"],
    "đái rắt": ["R30.9"],
    "tiểu rắt": ["R30.9"],
    "đái khó": ["R30.9"],
    "tiểu khó": ["R30.9"],
    "đái nhiều": ["R35"],
    "tiểu nhiều": ["R35"],
    "đái ít": ["R34"],
    "tiểu ít": ["R34"],
    "đái đêm": ["R35"],
    "tiểu đêm": ["R35"],
    "đái không tự chủ": ["R32"],
    "tiểu không tự chủ": ["R32"],
    "táo bón": ["K59.0"],
    "tiêu chảy": ["K59.1"],
    "buồn nôn": ["R11"],
    "nôn": ["R11"],
    "nôn ói": ["R11"],
    "nôn ra máu": ["K92.0"],
    "ói ra máu": ["K92.0"],
    "ói mửa": ["R11"],
    "nôn khan": ["R11"],
    "đau bụng": ["R10.4"],
    "đau bụng trên": ["R10.1"],
    "đau bụng dưới": ["R10.3"],
    "đau thượng vị": ["R10.1"],
    "đau hạ vị": ["R10.3"],
    "đau hố chậu": ["R10.3"],
    "đầy bụng": ["R14"],
    "chướng bụng": ["R14"],
    "trướng bụng": ["R14"],
    "ợ hơi": ["R14"],
    "ợ nóng": ["R12"],
    "ợ chua": ["R12"],
    "khó nuốt": ["R13"],
    "đau khi nuốt": ["R13"],
    "đau ngực": ["R07.9"],
    "đau sau xương ức": ["R07.9"],
    "nặng ngực": ["R07.9"],
    "tức ngực": ["R07.9"],
    "đánh trống ngực": ["R00.2"],
    "hồi hộp": ["R00.2"],
    "tim đập nhanh": ["R00.0"],
    "tim đập chậm": ["R00.1"],
    "tim đập không đều": ["R00.9"],
    "loạn nhịp": ["R00.9"],
    "ngất": ["R55"],
    "chóng mặt": ["R42"],
    "hoa mắt": ["R42"],
    "choáng": ["R42"],
    "mất thăng bằng": ["R26.0"],
    "đi loạng choạng": ["R26.0"],
    "rối loạn thăng bằng": ["R26.0"],
    "đau đầu": ["R51"],
    "đau nửa đầu": ["G43.9"],
    "đau đầu vận mạch": ["G44.1"],
    "đau đầu căng cơ": ["G44.2"],
    "đau đầu cluster": ["G44.0"],
    "đau cổ": ["M54.2"],
    "cứng cổ": ["M54.2"],
    "đau vai": ["M75.9"],
    "đau lưng": ["M54.5"],
    "đau thắt lưng": ["M54.5"],
    "đau cột sống": ["M54.5"],
    "đau khớp": ["M25.5"],
    "đau cơ": ["M79.1"],
    "đau xương": ["M89.9"],
    "đau tứ chi": ["R29.8"],
    "đau chân": ["R29.8"],
    "đau tay": ["R29.8"],
    "đau cánh tay": ["M79.3"],
    "đau cẳng tay": ["M79.3"],
    "đau đùi": ["M79.3"],
    "đau bắp chân": ["M79.3"],
    "đau bắp đùi": ["M79.3"],
    "đau bắp tay": ["M79.3"],
    "phù chân": ["R60.0"],
    "phù tay": ["R60.0"],
    "phù mặt": ["R60.0"],
    "phù cổ chân": ["R60.0"],
    "viêm mũi": ["J30.9"],
    "nghẹt mũi": ["R09.8"],
    "sổ mũi": ["R09.8"],
    "chảy nước mũi": ["R09.8"],
    "hắt hơi": ["R06.7"],
    "ngứa mũi": ["R09.8"],
    "viêm họng": ["J02.9"],
    "đau họng": ["R07.0"],
    "ngứa họng": ["R09.8"],
    "khô họng": ["R09.8"],
    "ho": ["R05"],
    "ho khan": ["R05"],
    "ho có đờm": ["R05"],
    "ho ra máu": ["R04.2"],
    "đờm": ["R09.8"],
    "đờm máu": ["R04.2"],
    "khó thở": ["R06.0"],
    "khó thở khi nằm": ["R06.0"],
    "khó thở khi gắng sức": ["R06.0"],
    "khó thở thanh quản": ["R06.0"],
    "thở rít": ["R06.2"],
    "khò khè": ["R06.2"],
    "hen": ["J45.9"],
    "hen suyễn": ["J45.9"],
    "hen phế quản": ["J45.9"],
    "viêm phế quản": ["J40"],
    "viêm phổi": ["J18.9"],
    "viêm tai giữa": ["H66.9"],
    "viêm tai": ["H66.9"],
    "đau tai": ["H92.0"],
    "ù tai": ["H93.1"],
    "điếc": ["H91.9"],
    "chảy mủ tai": ["H92.2"],
    "chảy máu tai": ["H92.2"],
    "viêm mắt": ["H10.9"],
    "đau mắt": ["H57.1"],
    "đỏ mắt": ["H57.1"],
    "ngứa mắt": ["H57.1"],
    "chảy nước mắt": ["H04.2"],
    "mờ mắt": ["H53.8"],
    "nhìn mờ": ["H53.8"],
    "nhìn đôi": ["H53.2"],
    "song thị": ["H53.2"],
    "mù": ["H54.7"],
    "giảm thị lực": ["H54.7"],
    "viêm kết mạc": ["H10.9"],
    "đau răng": ["K08.8"],
    "răng lung lay": ["K08.8"],
    "mất răng": ["K08.1"],
    "chảy máu chân răng": ["K06.8"],
    "viêm nướu": ["K05.1"],
    "hôi miệng": ["R19.6"],
    "khô miệng": ["R68.2"],
    "đắng miệng": ["R43.8"],
    "loét miệng": ["K12.0"],
    "nhiệt miệng": ["K12.0"],
    "viêm miệng": ["K12.1"],
    "viêm lợi": ["K05.1"],
    "viêm quanh răng": ["K05.6"],
    "viêm amidan": ["J03.9"],
    "sưng amidan": ["J03.9"],
    "áp xe amidan": ["J36"],
    "viêm thanh quản": ["J04.0"],
    "khàn tiếng": ["R49.0"],
    "mất tiếng": ["R49.1"],
    "viêm xoang": ["J32.9"],
    "đau xoang": ["J32.9"],
    "nghẹt mũi": ["R09.8"],
    "rối loạn tiền đình": ["H81.9"],
    "viêm tiền đình": ["H81.9"],
    "meniere": ["H81.0"],
    "ù tai": ["H93.1"],
    "chóng mặt": ["R42"],
    "rối loạn kinh nguyệt": ["N92.6"],
    "rong kinh": ["N92.0"],
    "thống kinh": ["N94.6"],
    "đau bụng kinh": ["N94.6"],
    "mất kinh": ["N91.2"],
    "vô kinh": ["N91.0"],
    "kinh nguyệt không đều": ["N92.6"],
    "hội chứng tiền kinh nguyệt": ["N94.3"],
    "mãn kinh": ["N95.1"],
    "tiền mãn kinh": ["N95.1"],
    "bốc hỏa": ["N95.1"],
    "khô âm đạo": ["N95.2"],
    "viêm âm đạo": ["N76.0"],
    "viêm cổ tử cung": ["N72"],
    "viêm phần phụ": ["N73.9"],
    "viêm vùng chậu": ["N73.9"],
    "u nang buồng trứng": ["N83.2"],
    "u xơ tử cung": ["D25.9"],
    "u xơ": ["D25.9"],
    "polyp tử cung": ["N84.0"],
    "polyp cổ tử cung": ["N84.1"],
    "ung thư cổ tử cung": ["C53.9"],
    "ung thư buồng trứng": ["C56"],
    "ung thư vú": ["C50.9"],
    "ung thư tử cung": ["C55"],
    "ung thư nội mạc tử cung": ["C54.1"],
    "thai ngoài tử cung": ["O00.9"],
    "chửa ngoài tử cung": ["O00.9"],
    "sảy thai": ["O03.9"],
    "dọa sảy thai": ["O20.0"],
    "động thai": ["O20.0"],
    "thai chết lưu": ["O36.4"],
    "sinh non": ["O60"],
    "đẻ non": ["O60"],
    "tiền sản giật": ["O14.9"],
    "tiền sản giật nặng": ["O14.1"],
    "sản giật": ["O15.9"],
    "nhiễm độc thai nghén": ["O26.9"],
    "ốm nghén": ["O26.9"],
    "đái tháo đường thai kỳ": ["O24.4"],
    "tăng huyết áp thai kỳ": ["O13"],
    "viêm âm đạo khi mang thai": ["O23.5"],
    "nhiễm khuẩn tiết niệu thai kỳ": ["O23.0"],
    "thiếu máu thai kỳ": ["O99.0"],
    "u xơ tuyến tiền liệt": ["D29.1"],
    "tăng sản tuyến tiền liệt": ["N40"],
    "phì đại tuyến tiền liệt": ["N40"],
    "ung thư tuyến tiền liệt": ["C61"],
    "viêm tuyến tiền liệt": ["N41.9"],
    "viêm tinh hoàn": ["N45.9"],
    "viêm mào tinh hoàn": ["N45.1"],
    "giãn tĩnh mạch thừng tinh": ["I86.1"],
    "thoát vị bẹn": ["K40.9"],
    "thoát vị": ["K40.9"],
    "tràn dịch màng tinh hoàn": ["N43.3"],
    "xuất tinh sớm": ["F52.4"],
    "rối loạn cương dương": ["F52.2"],
    "liệt dương": ["F52.2"],
    "vô sinh nam": ["N46"],
    "vô sinh nữ": ["N97.9"],
    "vô sinh": ["N97.9"],
    "hiếm muộn": ["N97.9"],
    "dị tật bẩm sinh": ["Q89.9"],
    "dị tật": ["Q89.9"],
    "hội chứng down": ["Q90.9"],
    "down": ["Q90.9"],
    "hội chứng turner": ["Q96.9"],
    "sứt môi": ["Q36.9"],
    "hở hàm ếch": ["Q35.9"],
    "khe hở vòm miệng": ["Q35.9"],
    "thoát vị não": ["Q01.9"],
    "não úng thủy": ["Q91.9"],
    "trật khớp háng": ["Q65.0"],
    "loạn dưỡng cơ": ["G71.0"],
    "teo cơ": ["M62.5"],
    "bại não": ["G80.9"],
    "liệt não": ["G80.9"],
    "chậm phát triển": ["R62.0"],
    "chậm phát triển trí tuệ": ["F79"],
    "chậm phát triển vận động": ["R62.0"],
    "thiếu men g6pd": ["D55.0"],
    "thiếu g6pd": ["D55.0"],
    "thiếu men": ["D55.0"],
    "g6pd": ["D55.0"],
    "thalassemia": ["D56.9"],
    "tan máu bẩm sinh": ["D56.9"],
    "tan máu": ["D58.9"],
    "hồng cầu liềm": ["D57.1"],
    "thiếu máu hồng cầu liềm": ["D57.1"],
    "bệnh tự miễn": ["D89.9"],
    "lupus": ["M32.9"],
    "lupus ban đỏ": ["M32.9"],
    "lupus ban đỏ hệ thống": ["M32.9"],
    "sle": ["M32.9"],
    "viêm khớp dạng thấp": ["M06.9"],
    "viêm đa khớp dạng thấp": ["M06.9"],
    "xơ cứng bì": ["M34.9"],
    "viêm da cơ": ["M33.9"],
    "viêm đa cơ": ["M33.9"],
    "hội chứng sjogren": ["M35.0"],
    "viêm mạch": ["I77.6"],
    "viêm mạch máu": ["I77.6"],
    "viêm động mạch": ["I77.6"],
    "viêm đa mạch": ["M31.9"],
    "u hạt": ["M31.3"],
    "viêm quanh động mạch": ["M31.4"],
    "bệnh behcet": ["M35.2"],
    "hội chứng antiphospholipid": ["D68.6"],
    "viêm cột sống dính khớp": ["M45"],
    "viêm khớp vảy nến": ["M07.3"],
    "viêm khớp phản ứng": ["M02.9"],
    "hội chứng reiter": ["M02.9"],
    "thấp khớp": ["I00"],
    "thấp tim": ["I00"],
    "sốt thấp khớp": ["I00"],
    "thấp khớp cấp": ["I00"],
    "viêm nội tâm mạc": ["I33.9"],
    "viêm nội tâm mạc nhiễm khuẩn": ["I33.0"],
    "viêm cơ tim": ["I51.4"],
    "viêm màng ngoài tim": ["I30.9"],
    "viêm màng tim": ["I30.9"],
    "tràn dịch màng tim": ["I30.9"],
    "tràn dịch màng ngoài tim": ["I31.3"],
    "chèn ép tim": ["I31.1"],
    "bệnh cơ tim": ["I42.9"],
    "cơ tim phì đại": ["I42.1"],
    "bệnh cơ tim phì đại": ["I42.1"],
    "bệnh cơ tim giãn": ["I42.0"],
    "bệnh cơ tim hạn chế": ["I42.5"],
    "viêm cơ tim do virus": ["I40.0"],
    "viêm cơ tim do vi khuẩn": ["I40.0"],
    "viêm cơ tim do nấm": ["I40.0"],
    "nhịp nhanh thất": ["I47.2"],
    "nhịp nhanh trên thất": ["I47.1"],
    "nhịp nhanh nhĩ": ["I47.1"],
    "ngoại tâm thu thất": ["I49.3"],
    "ngoại tâm thu nhĩ": ["I49.1"],
    "ngoại tâm thu": ["I49.1"],
    "rung thất": ["I49.0"],
    "cuồng thất": ["I49.0"],
    "xung động sớm": ["I49.1"],
    "block tim": ["I45.9"],
    "block a-v": ["I44.9"],
    "block nhĩ thất": ["I44.9"],
    "block nhĩ thất độ i": ["I44.0"],
    "block nhĩ thất độ ii": ["I44.1"],
    "block nhĩ thất độ iii": ["I44.2"],
    "block nhánh phải": ["I45.1"],
    "block nhánh trái": ["I44.4"],
    "hội chứng wolff-parkinson-white": ["I45.6"],
    "wpw": ["I45.6"],
    "hội chứng brugada": ["I47.2"],
    "đột tử": ["R96.0"],
    "đột tử do tim": ["I46.1"],
    "ngừng tim": ["I46.9"],
    "sốc tim": ["R57.0"],
    "sốc": ["R57.9"],
    "sốc phản vệ": ["T78.2"],
    "sốc nhiễm khuẩn": ["A41.9"],
    "sốc giảm thể tích": ["R57.1"],
    "ngộ độc": ["T65.9"],
    "ngộ độc thức ăn": ["A05.9"],
    "ngộ độc rượu": ["F10.9"],
    "ngộ độc thuốc": ["T50.9"],
    "dị ứng thuốc": ["T78.4"],
    "dị ứng": ["T78.4"],
    "phản vệ": ["T78.2"],
    "sốc phản vệ": ["T78.2"],
    "hen phế quản dị ứng": ["J45.9"],
    "viêm da tiếp xúc dị ứng": ["L23.9"],
    "viêm da dị ứng": ["L23.9"],
    "viêm kết mạc dị ứng": ["H10.1"],
    "viêm mũi dị ứng": ["J30.1"],
    "sốt cỏ khô": ["J30.1"],
    "mề đay mạn tính": ["L50.8"],
    "mề đay cấp tính": ["L50.8"],
    "mày đay mạn tính": ["L50.8"],
    "phù mạch": ["T78.3"],
    "phù quincke": ["T78.3"],
    "quá mẫn": ["T78.4"],
}

# Merge with existing ICD10_DICT
ICD10_DICT_EXPANDED = {**ICD10_DICT, **ADDITIONAL_ICD10}
ICD10_KEYS_SORTED_EXPANDED = sorted(ICD10_DICT_EXPANDED.keys(), key=lambda x: -len(x))