# -*- coding: utf-8 -*-
# vocab_v5.py - Extended medical vocabulary

SYMPTOMS = [
    "aphasia",
    "ban đỏ",
    "biến đổi ý thức",
    "biếng ăn",
    "bong gân",
    "buồn",
    "buồn ngủ",
    "buồn nôn",
    "buồn nôn nhẹ",
    "buồn nôn sau ăn",
    "bàn chân vẹo",
    "bàng quang căng",
    "béo phì",
    "bạch cầu tăng",
    "bất tỉnh",
    "bầm máu",
    "bầm tím",
    "bầm tím không rõ nguyên nhân",
    "bị ngã",
    "bọng nước",
    "bỏ bú",
    "bỏ ăn",
    "bỏng",
    "bối rối",
    "bồn chồn",
    "bụng báng",
    "canxi ion hóa tăng",
    "choáng",
    "choáng váng",
    "chuột rút",
    "chán ăn",
    "chân sonde dẫn lưu sưng nề, đỏ",
    "chóng mặt",
    "chóng mặt khi ngồi dậy",
    "chóng mặt khi thay đổi tư thế",
    "chóng mặt tư thế",
    "chóng mặt từng đợt",
    "chưa ra huyết âm đạo",
    "chưa rỉ ối",
    "chưa vỡ ối",
    "chướng bụng",
    "chướng hơi",
    "chảy dịch liên tục từ mặt trong của bàn chân",
    "chảy dịch tai",
    "chảy dịch vàng",
    "chảy máu",
    "chảy máu cam",
    "chảy máu chân răng",
    "chảy máu dạ dày",
    "chảy máu kéo dài",
    "chảy máu lâu",
    "chảy máu mũi",
    "chảy máu nhiều",
    "chảy máu tai",
    "chảy mũi",
    "chảy mủ",
    "chảy nước mũi",
    "chấn thương",
    "co giật",
    "co giật cục bộ",
    "co giật kiểu động kinh",
    "co thắt ngực",
    "cánh tay trái lơ lửng",
    "căng bụng",
    "căng cơ",
    "căng cứng vai trái",
    "căng thẳng",
    "căng tức vùng âm đạo",
    "cơn co tử cung",
    "cảm giác bí tiếu liên tục",
    "cảm giác bất thường ở bên phải đầu",
    "cảm giác chèn ép ngực",
    "cảm giác khát nước",
    "cảm giác như bị xịt nước ở ngực",
    "cảm giác nặng ngực",
    "cảm giác trầm",
    "cấu trúc vi nang",
    "cổ trướng",
    "cứng cổ",
    "cứng khớp",
    "cứng khớp buổi sáng",
    "cứng khớp gối",
    "cứng khớp ngón tay",
    "cứng lưng",
    "da dương tính",
    "da khô, nếp véo da mất chậm",
    "da vàng",
    "da âm tính",
    "dị ứng",
    "dịch rỉ huyết thanh",
    "gan to",
    "giai đoạn hưng cảm",
    "giai đoạn trầm cảm",
    "giảm dung nạp gắng sức",
    "giảm hứng thú",
    "giảm khả năng quan hệ tình dục",
    "giảm nhu cầu ngủ",
    "giảm thị lực",
    "giật",
    "giật cơ",
    "giật cơ nhẹ",
    "giọng khàn",
    "gãy xương",
    "gãy xương cẳng tay",
    "gãy xương sườn",
    "gãy xương đùi",
    "gần ngất",
    "gầy",
    "gầy cơ",
    "gầy sút",
    "gầy sút cân",
    "gập sâu",
    "gắng sức",
    "ho",
    "ho có đờm",
    "ho có đờm vàng",
    "ho có đờm xanh",
    "ho khan",
    "ho khan kéo dài",
    "ho máu",
    "ho máu tươi",
    "ho mạn tính",
    "ho ra máu",
    "ho ra máu tươi",
    "ho ra đờm",
    "ho ra đờm kèm máu",
    "ho đặc như bã",
    "hoa mắt",
    "hoa mắt khi đứng",
    "hoang tưởng",
    "hoàng đản",
    "hoại tử ngày càng nặng",
    "hoại tử đen",
    "hoạt động đau",
    "hoảng loạn",
    "hoảng sợ",
    "huyết trắng",
    "huyết áp cao",
    "huyết áp không ổn định",
    "hôn mê",
    "hưng cảm",
    "hạ huyết áp",
    "hạ thân nhiệt",
    "hẹp động mạch cảnh",
    "hồi hộp",
    "hồi hộp tim",
    "hụt hơi",
    "khàn tiếng",
    "khàn đặc",
    "khí hư",
    "khí hư bất thường",
    "khò khè",
    "khó chịu khi đi tiểu",
    "khó chịu khi đại tiện",
    "khó khăn khi ra khỏi giường",
    "khó khăn khi tự sinh hoạt",
    "khó khăn khi ăn uống qua đường miệng",
    "khó kiểm soát huyết áp",
    "khó ngủ",
    "khó nuốt",
    "khó phát âm",
    "khó thở",
    "khó thở khi gắng sức",
    "khó thở khi gắng sức nhẹ",
    "khó thở khi hoạt động",
    "khó thở khi ngủ",
    "khó thở khi nói",
    "khó thở khi nằm",
    "khó thở kéo dài",
    "khó thở liên tục",
    "khó thở nhẹ",
    "khó thở ra",
    "khó thở thanh quản",
    "khó thở tăng dần",
    "khó thở vào",
    "khó thở đường thở trên",
    "khó thở đột ngột",
    "khó tiêu",
    "khó vận động",
    "khó đi cầu",
    "khô âm đạo",
    "không nhận biết",
    "khối cứng trong âm đạo",
    "khối sa tại âm hộ",
    "khởi phát chuyển dạ",
    "kinh nguyệt không đều",
    "kinh nhiều",
    "kinh ít",
    "kém tỉnh táo",
    "kéo lê chân trái",
    "lan lên hàm",
    "leo cầu thang",
    "liệt",
    "liệt hai chân",
    "liệt nửa người",
    "liệt tứ chi",
    "lo lắng",
    "lo sợ",
    "lo âu",
    "loét",
    "loét 2 bàn chân",
    "loét chân",
    "loét da",
    "loét nhiễm trùng",
    "loét đau",
    "loét đỏ",
    "lách to",
    "lú lẫn",
    "lú lẫn từng đợt",
    "lạm dụng chất",
    "lạm dụng chất kích thích",
    "lạm dụng opioid",
    "lạnh run",
    "lừ đừ",
    "mạch nhanh",
    "mất cảm giác",
    "mất cảm giác ngon miệng",
    "mất hứng thú",
    "mất ngôn ngữ",
    "mất ngủ",
    "mất thăng bằng",
    "mất thị lực tạm thời",
    "mất tiếng",
    "mất trí nhớ",
    "mất trí nhớ chi tiết",
    "mất định hướng",
    "mệt",
    "mệt khi gắng sức",
    "mệt khi vận động",
    "mệt lả",
    "mệt mỏi",
    "mệt mỏi toàn thân",
    "mệt nhiều",
    "mồ hôi trộm",
    "mờ mắt",
    "mụn nước",
    "nghe kém",
    "nghĩ tự tử",
    "nghẹn",
    "nghẹt mũi",
    "nghẹt ngực",
    "nghẹt thở",
    "nghẽn tắc động mạch cảnh",
    "ngáy",
    "ngã",
    "ngã do cơ học",
    "ngón chân út",
    "ngón tay cái",
    "ngưng thở",
    "ngạt mũi",
    "ngất",
    "ngất do tim",
    "ngất khi thay đổi tư thế",
    "ngất xỉu",
    "ngất xỉu đột ngột",
    "ngủ không sâu",
    "ngủ nhiều",
    "ngủ nông",
    "ngủ ít",
    "ngứa",
    "ngứa da toàn thân nhiều",
    "ngứa lăn tăn",
    "ngứa ngoài da",
    "ngứa toàn thân",
    "ngừng thở",
    "ngừng thở khi ngủ",
    "ngực khó chịu",
    "ngực không thoải mái",
    "nhiễm khuẩn",
    "nhiễm trùng",
    "nhiễm trùng da",
    "nhiễm virus",
    "nhìn mờ",
    "nhìn đôi",
    "nhịp thở nhanh",
    "nhịp tim nhanh",
    "nhịp tim đứt quãng",
    "nhức mỏi",
    "nhức mỏi toàn thân",
    "nhức đầu",
    "niêm mạc vàng",
    "nuốt khó",
    "nuốt vướng",
    "nuốt đau",
    "nói khó",
    "nói không rõ",
    "nói lắp",
    "nóng khớp",
    "nóng rát thượng vị",
    "nôn",
    "nôn dịch vàng",
    "nôn khan",
    "nôn khan nhiều lần",
    "nôn ra máu",
    "nôn ra thức ăn",
    "nôn ra thức ăn và dịch dạ dày, không có máu",
    "nôn từng đợt sau khi ăn",
    "nôn ói",
    "nước tiểu có cặn",
    "nước tiểu sẫm",
    "nước tiểu sẫm màu",
    "nước tiểu vàng",
    "nước tiểu đục",
    "nấc",
    "nấc cụt",
    "nặng ngực",
    "nốt sần tuyến giáp",
    "nổi ban đỏ",
    "nổi mẩn",
    "nổi mẩn đỏ",
    "nổi mề đay",
    "phát ban",
    "phát ban dạng sởi",
    "phân có máu",
    "phân máu",
    "phân nâu dương tính guaiac",
    "phân sống",
    "phân đen",
    "phân đen nhầy",
    "phù",
    "phù chi",
    "phù chân",
    "phù chân trái",
    "phù gan",
    "phù hai bên",
    "phù hai chi dưới",
    "phù hai chân",
    "phù mắt cá chân",
    "phù mắt cá chân hai bên",
    "phù ngoại vi",
    "phù não",
    "phù nề",
    "phù nề hạ chi",
    "phù phổi",
    "phù tay",
    "phù toàn thân",
    "phù toàn thân tăng dần",
    "phỏng",
    "quấy khóc",
    "ra huyết âm đạo",
    "ra huyết âm đạo bất thường",
    "ra huyết âm đạo lượng ít",
    "ra máu âm đạo",
    "ra máu âm đạo sau mãn kinh",
    "ra mồ hôi đêm",
    "rong huyết",
    "rong kinh",
    "run",
    "run chi",
    "run khi vận động",
    "run rẩy",
    "run tay",
    "run tay chân",
    "rung giật",
    "rách dây chằng",
    "rát họng",
    "rét",
    "rét run",
    "rít",
    "rùng mình",
    "rễ thần kinh tổn thương",
    "rỉ ối",
    "rối loạn cương",
    "rối loạn cảm giác",
    "rối loạn cảm xúc",
    "rối loạn giấc ngủ",
    "rối loạn kinh nguyệt",
    "rối loạn lo âu",
    "rối loạn lưỡng cực",
    "rối loạn tiêu hóa",
    "rối loạn tiền đình",
    "rối loạn tiểu tiện",
    "rối loạn vận động",
    "rối loạn ý thức",
    "rối loạn ý thức thoáng qua",
    "rối loạn đông máu",
    "sa tử cung",
    "sa âm đạo",
    "song thị",
    "suy dinh dưỡng",
    "suy giảm trí nhớ",
    "suy hô hấp",
    "suy hô hấp cấp",
    "suy hô hấp mạn",
    "suy kiệt",
    "suy nhược",
    "suy nhược toàn thân",
    "suy thận ngày càng nặng",
    "sút cân",
    "sưng khớp",
    "sưng phù hai mắt cá chân",
    "sưng quanh khớp ức đòn",
    "sưng tấy đỏ",
    "sưng đầu gối",
    "sỏi",
    "sỏi mật",
    "sỏi thận",
    "sỏi tiết niệu",
    "sỏi túi mật",
    "sốt",
    "sốt cao",
    "sốt cao không hạ",
    "sốt cao rét run",
    "sốt không rõ nguyên nhân",
    "sốt không đáp ứng thuốc hạ sốt",
    "sốt kéo dài",
    "sốt kéo dài trên 7 ngày",
    "sốt nhẹ",
    "sốt phát ban",
    "sốt rét",
    "sốt rét run",
    "sốt sốc",
    "sốt từng cơn",
    "sốt về chiều",
    "sốt về đêm",
    "sốt đến",
    "sổ mũi",
    "sợ ánh sáng",
    "sụt cân",
    "sụt cân nhanh",
    "sụt cân nhiều kg",
    "tai nạn",
    "tai nạn giao thông",
    "tai nạn lao động",
    "tai nạn sinh hoạt",
    "teo cơ",
    "thai máy",
    "thai máy giảm",
    "thai máy tốt",
    "thiếu máu",
    "thiếu máu thiếu sắt",
    "thiếu oxy",
    "thiểu niệu",
    "thoát vị",
    "thoát vị đĩa đệm",
    "thường xuyên ngủ quên",
    "thắt chặt ngực",
    "thở chậm",
    "thở dốc",
    "thở dốc khi leo cầu thang",
    "thở gấp",
    "thở hụt",
    "thở khò khè",
    "thở khò khè ban đêm",
    "thở khó tăng dần",
    "thở không ra",
    "thở không đều",
    "thở mạnh",
    "thở ngắn",
    "thở nhanh",
    "thở ra khó",
    "thở vào khó",
    "tim nhịp nhanh đều",
    "tim đập bỏ nhịp",
    "tim đập chậm",
    "tim đập hỗn loạn",
    "tim đập không đều",
    "tim đập nhanh",
    "tim đập nhanh chóng",
    "tiêu chảy",
    "tiêu chảy 4-5 lần",
    "tiêu chảy nhiều lần",
    "tiếng rít",
    "tiếng rít về đêm",
    "tiếng thở rít",
    "tiểu buốt",
    "tiểu bọt",
    "tiểu dắt",
    "tiểu khó",
    "tiểu không ra",
    "tiểu không tự chủ",
    "tiểu máu",
    "tiểu nhiều",
    "tiểu nhiều lần",
    "tiểu ra máu không đau",
    "tiểu rát",
    "tiểu rắt",
    "tiểu tiện không tự chủ",
    "tiểu tiện ra sàn",
    "tiểu ít",
    "tiểu đêm",
    "tiểu đêm nhiều",
    "tiểu đục",
    "toàn trạng suy kiệt",
    "toát mồ hôi",
    "tràn dịch màng ngoài tim mức độ trung bình",
    "trào ngược",
    "trước nhập viện",
    "trướng bụng",
    "trầm cảm",
    "trầm cảm ngày càng nặng",
    "trầm cảm nặng",
    "trật khớp",
    "tuyến giáp to",
    "tuột sonde dẫn lưu ổ bụng",
    "tái nhợt",
    "táo bón",
    "táo bón nhiều ngày",
    "tê",
    "tê bì",
    "tê bì chân tay",
    "tê bì nửa mặt phải",
    "tê bì vùng trán phải",
    "tê bì ở cánh tay trái",
    "tê chân",
    "tê lưỡi",
    "tê mặt",
    "tê nửa người",
    "tê tay",
    "tê đầu chi",
    "tê đầu ngón chân",
    "tê đầu ngón tay",
    "tím môi",
    "tím mặt",
    "tím tái",
    "tím đầu ngón",
    "tăng calci máu",
    "tăng cân",
    "tăng cân nhanh",
    "tăng cân trở lại",
    "tăng hoạt động",
    "tăng huyết áp",
    "tăng kali máu",
    "tăng đánh trống ngực",
    "tổn thương chi dưới",
    "tổn thương dây thanh quản",
    "tổn thương dạng bóng nước",
    "tụ máu dưới da",
    "tụt huyết áp",
    "tức ngực",
    "tự bắn vào đầu",
    "u buồng trứng",
    "u gan",
    "u não",
    "u phổi",
    "u thận",
    "va đập",
    "viêm dạ dày",
    "viêm gan",
    "viêm gan virus",
    "viêm họng",
    "viêm loét dạ dày",
    "viêm phổi mắc phải",
    "viêm tai giữa",
    "viêm tuyến mồ hôi",
    "viêm túi mật",
    "viêm tụy",
    "viêm tụy cấp",
    "viêm xoang",
    "vàng da",
    "vàng da không đau",
    "vàng da nhẹ",
    "vàng da nặng",
    "vàng mắt",
    "vàng niêm mạc",
    "váng đầu",
    "váng đầu khi thay đổi tư thế",
    "vã mồ hôi",
    "vô kinh",
    "vẹo bẩm sinh",
    "vẹo chân",
    "vẹo ngón",
    "vết thương",
    "vết thương hở",
    "vết thương phần mềm",
    "vết thương thấu bụng",
    "vết thương thấu bụng giữa bên phải",
    "vỡ ối",
    "vụng về",
    "xanh tím",
    "xuất huyết",
    "xuất huyết dưới da",
    "xuất huyết dạ dày",
    "xuất huyết tiêu hoá dưới",
    "xuất huyết tiêu hóa",
    "xơ vữa động mạch cảnh",
    "xỉu",
    "yếu",
    "yếu chân",
    "yếu chân phải",
    "yếu cơ",
    "yếu nửa người",
    "yếu nửa người trái",
    "yếu sức",
    "yếu tay",
    "yếu tay trái",
    "yếu toàn thân",
    "ói",
    "ói mửa",
    "ói ra máu",
    "ù hai bên tai",
    "ù một bên tai",
    "ù tai",
    "ù tai hai bên",
    "ù tai liên tục",
    "ù tai một bên",
    "ý nghĩ tự tử",
    "ý thức chậm hơn",
    "ý định tự tử",
    "ăn không ngon miệng",
    "ăn uống kém",
    "ăn vào dễ nôn",
    "đau buốt khi đi tiểu",
    "đau bánh chè",
    "đau bẹn trái",
    "đau bụng",
    "đau bụng dưới",
    "đau bụng dữ dội",
    "đau bụng gián đoạn",
    "đau bụng kinh",
    "đau bụng liên tục",
    "đau bụng ngày càng nặng",
    "đau bụng quanh rốn",
    "đau bụng trên",
    "đau bụng từng cơn",
    "đau bụng vùng hạ sườn phải ngày càng tăng",
    "đau bụng âm ỉ",
    "đau bụng âm ỉ quanh rốn sau khí uống sữa",
    "đau bụng âm ỉ vùng quanh rốn",
    "đau chân",
    "đau cơ",
    "đau cơ bắp chân",
    "đau cơ bắp tay",
    "đau cổ",
    "đau cổ vai",
    "đau cổ vai gáy",
    "đau cột sống thắt lưng",
    "đau dai dẳng",
    "đau gối",
    "đau gối hai bên",
    "đau hai bàn chân",
    "đau háng",
    "đau hông",
    "đau hông phải",
    "đau hông từng cơn",
    "đau hạ sườn",
    "đau hạ sườn phải",
    "đau hạ sườn phải liên tục",
    "đau hạ sườn phải tái phát",
    "đau hạ sườn trái",
    "đau hạ sườn trái từng cơn",
    "đau hạ vị",
    "đau hạ vị phải",
    "đau họng",
    "đau hố chậu",
    "đau khi quan hệ",
    "đau khi sờ nắn",
    "đau khi sờ nắn xung quanh vị trí đặt ống dẫn",
    "đau khi thay đổi tư thế",
    "đau khi tiểu",
    "đau khi ấn xoang",
    "đau khuỷu",
    "đau khớp",
    "đau khớp gối",
    "đau khớp háng",
    "đau khớp vai",
    "đau kiểu bóp nghẹt",
    "đau lan ra hông",
    "đau lan ra sau lưng",
    "đau lan vào sườn trái",
    "đau liên tục, lan tỏa ra lưng và có tính chất kéo",
    "đau lưng",
    "đau lưng dưới",
    "đau mắt",
    "đau một bên đầu",
    "đau ngực",
    "đau ngực khi thở",
    "đau ngực kiểu bóp nghẹt",
    "đau ngực kiểu thiếu máu",
    "đau ngực lan lên",
    "đau ngực lan ra",
    "đau ngực nhói bên trái lan xuống cánh tay trái",
    "đau ngực phải",
    "đau ngực sau xương ức",
    "đau ngực trái",
    "đau ngực trái dữ dội lan xuống cánh tay trái",
    "đau ngực ít",
    "đau nhiều khi giao hợp",
    "đau nhói",
    "đau nhói lồng ngực",
    "đau nhói ngực",
    "đau nhức",
    "đau nhức mỏi gối",
    "đau nhức xương khớp",
    "đau nửa đầu",
    "đau quanh rốn",
    "đau quanh vết mổ",
    "đau quặn",
    "đau quặn bụng",
    "đau rát khi đi tiểu",
    "đau răng",
    "đau sau xương ức",
    "đau sau đầu",
    "đau tai",
    "đau tay",
    "đau thượng vị",
    "đau thượng vị lan ra sau lưng",
    "đau thắt lưng",
    "đau thắt lưng hai bên",
    "đau thắt lưng một bên",
    "đau thắt ngực",
    "đau thắt ngực không ổn định",
    "đau thắt ngực ổn định",
    "đau thắt vùng rốn",
    "đau toàn thân ít",
    "đau tăng dần khi đi lại",
    "đau tức bụng dưới",
    "đau vai",
    "đau vai gáy",
    "đau vai phải",
    "đau vùng bánh chè",
    "đau vùng gan phải",
    "đau vùng hạ sườn phải",
    "đau vùng hạ sườn trái",
    "đau vùng thượng vị",
    "đau vùng thận",
    "đau vùng trước tim",
    "đau vùng xoang",
    "đau xoang",
    "đau xương bánh chè",
    "đau âm ỉ",
    "đau đầu",
    "đau đầu căng cơ",
    "đau đầu dữ dội",
    "đau đầu gối",
    "đau đầu gối phải",
    "đau đầu gối trái",
    "đau đầu kiểu migraine",
    "đau đầu kéo dài",
    "đau đầu migraine",
    "đau đầu nặng",
    "đau đầu tăng dần",
    "đau đầu vận mạch",
    "đau ấn vùng mổ",
    "đau ở sau đầu và cổ",
    "đi cầu phân lỏng",
    "đi cầu phân đen",
    "đi cầu ra máu",
    "đi khập khiễng cách quãng",
    "đi lại khó khăn",
    "đi lại không vững",
    "đi ngoài lỏng",
    "đi ngoài phân lỏng",
    "đi ngoài phân lỏng, toàn nước, không nhầy máu",
    "đi ngoài ra máu",
    "đi tiểu nhiều lần vào ban đêm",
    "điếc",
    "đái buốt",
    "đái khó",
    "đái không tự chủ",
    "đái máu",
    "đái nhiều",
    "đái đêm",
    "đánh trống ngực",
    "đánh trống ngực khi gắng sức",
    "đánh trống ngực liên hồi",
    "đánh trống ngực liên tục",
    "đánh trống ngực từng cơn",
    "đường huyết thấp",
    "đầy bụng",
    "đầy hơi",
    "đập ngực",
    "đổ mồ hôi",
    "đổ mồ hôi hột",
    "đổ mồ hôi đêm",
    "động kinh",
    "đột ngột xuất hiện đau bụng hạ sườn phải",
    "đờm ở cổ họng",
    "ảo giác",
    "ảo thanh",
    "ảo thị",
    "ỉa chảy",
    "ối vỡ non",
    "ớn lạnh",
    "ợ chua",
    "ợ hơi",
    "ợ nóng",
]

DIAGNOSES = [
    "Zona thần kinh",
    "addison",
    "alzheimer",
    "basedow",
    "biến chứng thuyên tắc phổi hai bên",
    "block nhĩ thất",
    "block nhĩ thất cấp",
    "block tim",
    "bong gân",
    "bong gân cổ chân",
    "bong gân đầu gối",
    "bàn chân vẹo",
    "bàn chân vẹo bẩm sinh",
    "bàng quang thần kinh gây biến chứng liệt hai chi dưới",
    "béo phì",
    "béo phì độ 1",
    "béo phì độ 2",
    "bóc tách động mạch chủ",
    "bướu",
    "bướu giáp",
    "bất thường điện giải",
    "bầm dập nhu mô",
    "bệnh ba thân động mạch vành nghiêm trọng",
    "bệnh basedow",
    "bệnh bạch cầu dòng tủy mãn tính",
    "bệnh gan do rượu",
    "bệnh gút không đặc hiệu",
    "bệnh huntington",
    "bệnh lý bk",
    "bệnh lý khớp gối",
    "bệnh lý thần kinh ngoại biên",
    "bệnh mạch máu ngoại biên",
    "bệnh mạch vành",
    "bệnh parkinson",
    "bệnh phổi kẽ",
    "bệnh phổi tắc nghẽn mạn tính",
    "bệnh thần kinh ngoại biên",
    "bệnh thần kinh tự chủ",
    "bệnh thận mạn",
    "bệnh thận đa nang",
    "bệnh thủy đậu",
    "bệnh tim mạch",
    "bệnh tim mạch do xơ vữa",
    "bệnh tim thiếu máu",
    "bệnh tim thiếu máu cơ tim",
    "bệnh tim thiếu máu cục bộ",
    "bệnh động mạch vành",
    "bệnh động mạch vành mạn tính",
    "bỏng",
    "bỏng độ 1",
    "bỏng độ 2",
    "bỏng độ 3",
    "chèn ép tim",
    "chèn ép tủy",
    "chảy máu não",
    "chấn thương bụng hở",
    "chấn thương bụng kín",
    "chấn thương cột sống cổ",
    "chấn thương gãy xương sườn trái",
    "chấn thương ngực kín",
    "chấn thương phần mềm",
    "chấn thương sọ não",
    "chấn thương tù",
    "chấn thương đầu",
    "chứng hay quên",
    "copd",
    "cushing",
    "cuồng nhĩ",
    "cơn đau thắt ngực không ổn định",
    "cườm",
    "cường cận giáp",
    "cường cận giáp nguyên phát",
    "cường giáp",
    "cổ trướng",
    "di căn não",
    "dị ứng phấn hoa",
    "dị ứng theo mùa",
    "gan nhiễm mỡ",
    "gerd",
    "ghép thận thất bại",
    "giai đoạn giống hưng cảm",
    "giãn tĩnh mạch chi dưới",
    "giãn đường dẫn mật trong gan",
    "giả gout",
    "giảm HDL",
    "giảm chức năng tâm thu thất trái nghiêm trọng",
    "giảm tiểu cầm",
    "glaucoma",
    "graft SVG bị tắc",
    "gãy cổ xương đùi di lệch",
    "gãy nứt xương",
    "gãy xương",
    "gãy xương chậu",
    "gãy xương cẳng tay",
    "gãy xương cổ xương đùi",
    "gãy xương cột sống",
    "gãy xương hở",
    "gãy xương kín",
    "gãy xương sườn",
    "gãy xương vụn",
    "gãy xương đòn",
    "gãy xương đùi",
    "gầy",
    "hen",
    "hen phế quản",
    "hen phổi",
    "hen suyễn",
    "hen tim",
    "hoang tưởng",
    "hoại tử tụy",
    "huntington",
    "huyết khối tĩnh mạch",
    "hưng cảm",
    "hưng cảm nhẹ",
    "hạ canxi máu",
    "hạ huyết áp",
    "hạ kali máu",
    "hạ magne máu",
    "hạ natri máu",
    "hạ đường huyết",
    "hạ đường huyết không triệu chứng",
    "hạ đường huyết nặng",
    "hẹp van động mạch chủ nghiêm trọng",
    "hẹp động mạch cảnh",
    "hẹp động mạch cảnh chung trái",
    "hẹp ống sống",
    "hội chứng chuyển hóa",
    "hội chứng cushing",
    "hội chứng kháng enzym tổng hợp protein",
    "hội chứng mạch vành cấp",
    "hội chứng nghiện rượu",
    "hội chứng ruột kích thích",
    "hội chứng thận hư",
    "hội chứng thận hư nhiễm mỡ",
    "hội chứng turner",
    "hội chứng vành cấp",
    "hội chứng đáp ứng viêm toàn thân",
    "hội chứng ống cổ tay",
    "hở van hai lá nặng",
    "khí phế thũm",
    "khí thũm",
    "khối máu tụ dưới màng cứng bán cấp",
    "khối u",
    "khối u có nguồn gốc từ đường mật tụy",
    "khối u thần kinh nội tiết ở thân tụy",
    "khối u trực tràng",
    "lao kháng thuốc",
    "lao phổi",
    "lao phổi mới",
    "leukemia",
    "liệt dây thanh",
    "loãng xương",
    "loãng xương nặng",
    "loét bàn chân nhiễm trùng",
    "loét chân",
    "loét do tì đè",
    "loét dạ dày",
    "loét dạ dày tá tràng",
    "loét hành tá tràng",
    "loét hồi tràng",
    "loét không liền miệng",
    "loét thực quản",
    "loét tá tràng",
    "loét tì đè giai đoạn IV mãn tính",
    "loạn dưỡng cơ",
    "loạn nhịp tim",
    "loạn nhịp xoang",
    "loạn thần",
    "lymphoma",
    "lymphoma hodgkin",
    "lymphoma không hodgkin",
    "lymphoma tế bào B",
    "lymphoma tế bào T",
    "lạm dụng chất",
    "lạm dụng opioid",
    "lạm dụng thuốc",
    "migraine",
    "màng phổi dày dính",
    "nang màng nhện",
    "nghiện opioid",
    "nghiện thuốc",
    "nghẽn tắc và hẹp động mạch cảnh",
    "nghẽn tắc động mạch cảnh",
    "ngoại tâm thu",
    "ngoại tâm thu nhĩ",
    "ngoại tâm thu thất",
    "ngưng thở khi ngủ do tắc nghẽn",
    "ngất xỉu do phản ứng thần kinh mạch máu",
    "ngừng thở khi ngủ",
    "nhiễm Clostridioides difficile",
    "nhiễm cryptosporidium",
    "nhiễm khuẩn",
    "nhiễm khuẩn huyết",
    "nhiễm khuẩn huyết do tụ cầu vàng nhạy cảm methicillin",
    "nhiễm khuẩn đường tiết niệu",
    "nhiễm khuẩn đường tiết niệu có các vi khuẩn hỗn hợp",
    "nhiễm trùng",
    "nhiễm trùng chi dưới bên phải do Enterococcus kháng vancomycin",
    "nhiễm trùng huyết",
    "nhiễm trùng huyết đường vào tiết niệu",
    "nhiễm trùng mô mềm",
    "nhiễm trùng vết mổ",
    "nhiễm trùng xương",
    "nhiễm trùng đường hô hấp trên",
    "nhiễm trùng đường tiết niệu kháng thuốc",
    "nhiễm trùng ổ bụng",
    "nhiễm virus Herpes simplex",
    "nhiễm độc giáp",
    "nhược cơ",
    "nhịp chậm",
    "nhịp chậm xoang",
    "nhịp nhanh",
    "nhịp nhanh trên thất",
    "nhịp nhanh xoang",
    "nhịp xoang",
    "nhịp xoang chiếm ưu thế",
    "nhịp xoang không đều",
    "nhồi máu cũ nhỏ ở vỏ não đỉnh trái",
    "nhồi máu cơ tim",
    "nhồi máu cơ tim ST chênh lên",
    "nhồi máu cơ tim ST không chênh lên",
    "nhồi máu cơ tim bán cấp",
    "nhồi máu cơ tim có ST chênh lên",
    "nhồi máu cơ tim cũ",
    "nhồi máu cơ tim cấp",
    "nhồi máu cơ tim không ST chênh lên",
    "nhồi máu não",
    "nhồi máu não cũ",
    "nhồi máu não cấp",
    "overdose thuốc",
    "parkinson",
    "phì đại tuyến tiền liệt",
    "phình mạch ACom",
    "phình động mạch chủ",
    "phình động mạch chủ ngực",
    "phỏng",
    "phổi khí thũm",
    "polyp mũi",
    "protein niệu",
    "rung nhĩ",
    "rung nhĩ kịch phát",
    "rung nhĩ mạn",
    "rách dây chằng",
    "rách dây chằng chéo sau",
    "rách dây chằng chéo trước",
    "rò động tĩnh mạch",
    "rò ống tuỵ mật",
    "rối loạn chuyển hóa",
    "rối loạn chức năng thất trái",
    "rối loạn chức năng tâm thất phải",
    "rối loạn cảm xúc",
    "rối loạn cảm xúc lưỡng cực",
    "rối loạn dẫn truyền",
    "rối loạn giấc ngủ",
    "rối loạn hưng cảm",
    "rối loạn lipid máu",
    "rối loạn lo âu",
    "rối loạn lo âu tổng quát",
    "rối loạn lưỡng cực",
    "rối loạn nhịp",
    "rối loạn nhịp tim",
    "rối loạn panic",
    "rối loạn thần kinh thực vật",
    "rối loạn thần kinh tim",
    "rối loạn tiền đình",
    "rối loạn điện giải",
    "rối loạn đông máu",
    "sa sút trí tuệ",
    "sa sút trí tuệ giai đoạn cuối",
    "sa trực tràng",
    "sa tử cung",
    "sa van hai lá",
    "sa âm đạo",
    "suy cận giáp",
    "suy dinh dưỡng",
    "suy gan",
    "suy gan cấp",
    "suy gan mạn",
    "suy giáp",
    "suy giáp trung ương",
    "suy giảm miễn dịch",
    "suy hô hấp",
    "suy hô hấp cấp",
    "suy hô hấp mạn",
    "suy hô hấp type 1",
    "suy hô hấp type 2",
    "suy kiệt",
    "suy kiệt do ung thư",
    "suy nhược",
    "suy thượng thận",
    "suy thận",
    "suy thận cấp",
    "suy thận giai đoạn cuối",
    "suy thận mạn",
    "suy thận đa chulf",
    "suy tim",
    "suy tim cấp",
    "suy tim cấp trên mạn",
    "suy tim dãn tâm thu giữ nguyên trương lực",
    "suy tim không do thiếu máu cơ tim",
    "suy tim mạn",
    "suy tim sung huyết",
    "suy tim sung huyết cấp",
    "suy tim tâm thu",
    "suy tim độ 1",
    "suy tim độ 2",
    "suy tim độ 3",
    "suy tim độ 4",
    "suy tĩnh mạch",
    "sóng ST chênh xuống",
    "sỏi bàng quang",
    "sỏi mật",
    "sỏi niệu quản",
    "sỏi thận",
    "sỏi tiết niệu",
    "sỏi túi mật",
    "sốc giảm thể tích",
    "sốc nhiễm trùng",
    "sốc phản vệ",
    "sốc tim",
    "tai biến",
    "tai biến mạch máu não",
    "tai nạn giao thông",
    "tai nạn lao động",
    "tai nạn sinh hoạt",
    "teo não",
    "thai 41 tuần",
    "theo dõi đại tràng giãn",
    "thiếu máu",
    "thiếu máu cơ tim",
    "thiếu máu cơ tim cục bộ",
    "thiếu máu cấp",
    "thiếu máu mạn",
    "thiếu máu nhẹ",
    "thiếu máu não",
    "thiếu máu nặng",
    "thiếu máu tan huyết",
    "thiếu máu thiếu sắt",
    "thoái hóa cột sống",
    "thoái hóa hoàng điểm",
    "thoái hóa khớp",
    "thoái hóa khớp gối",
    "thoái hóa khớp háng",
    "thoái hóa não",
    "thoái hóa tủy",
    "thoái hóa xương",
    "thoái hóa đa hệ thống",
    "thoái hóa đốt sống cổ",
    "thoát vị bẹn",
    "thoát vị hoành",
    "thoát vị rốn",
    "thoát vị thành bụng",
    "thoát vị đùi",
    "thoát vị đĩa đệm",
    "thoát vị đĩa đệm cột sống thắt lưng",
    "thuyên tắc phổi",
    "thuyên tắc phổi cấp",
    "thuyên tắc tĩnh mạch sâu",
    "thủng dạ dày",
    "thủng ruột non",
    "tiểu đường",
    "tiểu đường thai kỳ",
    "tràn dịch màng phổi",
    "tràn dịch màng phổi lượng ít",
    "tràn dịch màng phổi trái tái phát",
    "tràn dịch màng tim",
    "tràn dịch ổ bụng",
    "tràn khí màng phổi",
    "trào ngược",
    "trào ngược dạ dày thực quản",
    "trào ngược dịch mật",
    "trĩ",
    "trĩ hỗn hợp",
    "trĩ ngoại",
    "trĩ nội",
    "trầm cảm",
    "trầm cảm nặng",
    "trầm cảm tái phát",
    "trật khớp",
    "trật khớp gối",
    "trật khớp háng",
    "trật khớp vai",
    "tách thành động mạch chủ",
    "táo bón mãn tính",
    "tâm thần",
    "tâm thần phân liệt",
    "túi mật giãn",
    "tăng LDL",
    "tăng bilirubin máu",
    "tăng cholesterol máu",
    "tăng cholesterol máu đơn thuần",
    "tăng gánh tuần hoàn phổi",
    "tăng huyết áp",
    "tăng huyết áp kháng trị",
    "tăng huyết áp nguyên phát",
    "tăng huyết áp phổi",
    "tăng huyết áp thứ phát",
    "tăng huyết áp vô căn",
    "tăng huyết áp ác tính",
    "tăng huyết áp độ 1",
    "tăng huyết áp độ 2",
    "tăng huyết áp độ 3",
    "tăng kali máu",
    "tăng men gan",
    "tăng natri máu",
    "tăng sản tuyến tiền liệt",
    "tăng tiểu cầu",
    "tăng triglyceride",
    "tăng áp lực tĩnh mạch cửa",
    "tăng áp lực động mạch phổi",
    "tăng áp động mạch phổi",
    "tăng áp động mạch phổi mức độ trung bình",
    "tăng đường huyết",
    "tắc hẹp động mạch thận trái",
    "tắc mạch huyết khối",
    "tắc mạch phổi",
    "tắc nghẽn chỗ nối mật tụy",
    "tế bào bất thường",
    "tổn thương bánh chè đùi",
    "tổn thương dây thanh quản",
    "tổn thương tiêu xương lan tỏa",
    "tụ dịch dưới màng cứng mạn tính",
    "tụ máu dưới màng cứng mạn tính",
    "tụ máu ngoài màng cứng cấp tính",
    "tụt huyết áp",
    "u Sacoit tim",
    "u buồng trứng",
    "u cơ trơn tử cung",
    "u di căn",
    "u dây thần kinh số VIII",
    "u lympho",
    "u lympho không hodgkin tế bào B lớn lan toả",
    "u lành",
    "u lành tính",
    "u màng não",
    "u nang",
    "u nang buồng trứng",
    "u nang cạnh buồng trứng",
    "u nguyên phát",
    "u não",
    "u phổi",
    "u thần kinh",
    "u trung thất",
    "u trung thất trước",
    "u tuyến",
    "u tuyến giáp",
    "u tuyến yên",
    "u vú",
    "u xơ",
    "u xơ tuyến tiền liệt",
    "u xơ tử cung",
    "u xơ vú",
    "u ác",
    "u ác của tuyến tiền liệt",
    "u ác của đại tràng",
    "u ác của đầu tuỵ",
    "ung thư",
    "ung thư biểu mô tuyến đại tràng",
    "ung thư biểu mô tuyến, biệt hóa vừa phải đến kém",
    "ung thư biểu mô tế bào mật",
    "ung thư biểu mô tế bào vảy xâm nhập của dương vật",
    "ung thư buồng trứng",
    "ung thư bàng quang",
    "ung thư bạch huyết",
    "ung thư cổ tử cung",
    "ung thư da",
    "ung thư dạ dày",
    "ung thư gan",
    "ung thư hạch",
    "ung thư miệng",
    "ung thư máu",
    "ung thư nội mạc tử cung",
    "ung thư phần mềm",
    "ung thư phổi",
    "ung thư phổi không tế bào nhỏ",
    "ung thư thanh quản",
    "ung thư thận",
    "ung thư thực quản",
    "ung thư trực tràng",
    "ung thư tuyến giáp",
    "ung thư tuyến tiền liệt",
    "ung thư tá tràng",
    "ung thư tế bào gan",
    "ung thư tụy",
    "ung thư vòm họng",
    "ung thư vú",
    "ung thư vú trái",
    "ung thư xương",
    "ung thư đường mật",
    "ung thư đại tràng",
    "ung thư đại tràng sigma",
    "viêm amidan",
    "viêm bao hoạt dịch",
    "viêm buồng trứng",
    "viêm bàng quang",
    "viêm bàng quang cấp",
    "viêm bàng quang mạn",
    "viêm bể thận",
    "viêm cân gan chân",
    "viêm cơ",
    "viêm cơ mủ",
    "viêm cơ nhiễm khuẩn",
    "viêm cơ tim",
    "viêm cơ tim cấp",
    "viêm cơ tim mạn",
    "viêm cầu thận",
    "viêm cầu thận cấp",
    "viêm cầu thận mạn",
    "viêm da",
    "viêm da bội nhiễm",
    "viêm da cơ địa",
    "viêm da do ánh sáng",
    "viêm da dị ứng",
    "viêm da tiếp xúc",
    "viêm dây thần kinh",
    "viêm dây thần kinh ngoại biên",
    "viêm dạ dày",
    "viêm dạ dày cấp",
    "viêm dạ dày mạn",
    "viêm dạ dày ruột",
    "viêm dạ dày ruột do virus",
    "viêm gan",
    "viêm gan b",
    "viêm gan c",
    "viêm gan do rượu",
    "viêm gan siêu vi",
    "viêm gan siêu vi B",
    "viêm gan siêu vi C",
    "viêm gan tự miễn",
    "viêm gan virus",
    "viêm gan virus C và B",
    "viêm giác mạc",
    "viêm giác mạc loét",
    "viêm gân",
    "viêm gân gót",
    "viêm họng",
    "viêm họng do liên cầu",
    "viêm khớp",
    "viêm khớp dạng thấp",
    "viêm khớp nhiễm khuẩn",
    "viêm khớp nhiễm trùng",
    "viêm khớp vẩy nến",
    "viêm kết mạc",
    "viêm kết mạc dị ứng",
    "viêm loét bờ cong nhỏ dạ dày",
    "viêm loét đại tràng",
    "viêm màng bồ đào",
    "viêm màng ngoài tim",
    "viêm màng nhện tủy",
    "viêm màng não",
    "viêm màng não lao",
    "viêm màng não mủ",
    "viêm màng não siêu vi",
    "viêm màng não vi khuẩn",
    "viêm màng tim",
    "viêm mô tế bào",
    "viêm mũi",
    "viêm mũi dị ứng",
    "viêm mũi quá mẫn",
    "viêm mạch",
    "viêm niệu đạo",
    "viêm niệu đạo do lậu",
    "viêm niệu đạo không lậu",
    "viêm não",
    "viêm não do HSV",
    "viêm nội tâm mạc",
    "viêm nội tâm mạc cấp",
    "viêm nội tâm mạc mạn",
    "viêm phúc mạc",
    "viêm phần phụ",
    "viêm phế quản",
    "viêm phế quản co thắt",
    "viêm phế quản cấp",
    "viêm phế quản mạn",
    "viêm phế quản phổi",
    "viêm phổi",
    "viêm phổi bệnh viện",
    "viêm phổi cấp",
    "viêm phổi cộng đồng",
    "viêm phổi kẽ",
    "viêm phổi mô kẽ",
    "viêm phổi mạn",
    "viêm phổi mắc phải",
    "viêm phổi mắc phải cộng đồng",
    "viêm phổi thùy",
    "viêm phổi thùy dưới phải",
    "viêm ruột",
    "viêm ruột non",
    "viêm ruột non cấp",
    "viêm ruột thừa",
    "viêm ruột thừa cấp",
    "viêm ruột thừa peritonitis",
    "viêm tai giữa",
    "viêm tai giữa có mủ",
    "viêm tai giữa cấp",
    "viêm tai ngoài",
    "viêm thanh quản",
    "viêm thận",
    "viêm thận mạn",
    "viêm thực quản",
    "viêm thực quản trào ngược",
    "viêm thực quản độ C",
    "viêm tuyến giáp",
    "viêm tuyến giáp de quervain",
    "viêm tuyến giáp hashimoto",
    "viêm tuyến mồ hôi",
    "viêm tuyến mồ hôi mủ",
    "viêm tá tràng",
    "viêm túi mật",
    "viêm túi mật cấp",
    "viêm túi mật thủng cấp tính",
    "viêm tĩnh mạch",
    "viêm tắc động mạch",
    "viêm tụy",
    "viêm tụy cấp",
    "viêm tụy cấp nặng",
    "viêm tụy hoại tử",
    "viêm tụy mạn",
    "viêm tủy",
    "viêm tủy xương",
    "viêm tủy xương mãn tính",
    "viêm vòi trứng",
    "viêm xoang",
    "viêm xoang dị ứng",
    "viêm xoang hàm",
    "viêm xương",
    "viêm đa dây thần kinh",
    "viêm đa khớp",
    "viêm đường mật",
    "viêm đường mật tắc nghẽn",
    "viêm đường tiết niệu",
    "viêm đại tràng",
    "viêm đại tràng loét",
    "viêm đại tràng mạn",
    "vết thương",
    "vết thương hở",
    "vết thương phần mềm",
    "vết thương thấu bụng",
    "vết thương xuyên thủng",
    "xuất huyết dưới màng cứng",
    "xuất huyết dưới nhện",
    "xuất huyết dạ dày",
    "xuất huyết não",
    "xuất huyết não cấp",
    "xuất huyết nội sọ",
    "xuất huyết nội sọ không do chấn thương",
    "xuất huyết thất",
    "xuất huyết tiêu hóa",
    "xuất huyết tiêu hóa dưới",
    "xuất huyết tiêu hóa trên",
    "xơ cứng cột bên",
    "xơ gan",
    "xơ gan bù",
    "xơ gan mất bù",
    "xơ phổi",
    "xơ phổi không rõ nguyên nhân",
    "xơ phổi mô kẽ",
    "xơ vữa mạch máu ngoại biên",
    "xơ vữa mạch vành",
    "xơ vữa mảng loét",
    "xơ vữa động mạch",
    "xơ vữa động mạch cảnh",
    "xơ vữa động mạch vành",
    "xẹp phổi",
    "áp xe",
    "áp xe phổi",
    "áp xe vùng chậu",
    "ù tai",
    "ù tai subjective",
    "đa u tuỷ xương",
    "đa xơ cứng",
    "đau dây thần kinh liên sườn",
    "đau nửa đầu",
    "đau thần kinh sciatica",
    "đau thần kinh tọa",
    "đau thắt ngực không ổn định",
    "đau thắt ngực ổn định",
    "đau đầu migraine",
    "điếc",
    "điếc cảm giáng",
    "điếc thần kinh",
    "đào thải ghép thận",
    "đái tháo đường",
    "đái tháo đường không kiểm soát",
    "đái tháo đường kiểm soát kém",
    "đái tháo đường thai kỳ",
    "đái tháo đường type 1",
    "đái tháo đường type 2",
    "đái tháo đường type II",
    "đái tháo đường típ 1 có biến chứng viêm thần kinh ngoại biên",
    "đường huyết cao",
    "đường huyết không kiểm soát",
    "định lượng IgA tăng cao trong bệnh đa u tuỷ xương",
    "độ dày niêm mạc xoang hàm dày lên",
    "động kinh",
    "động kinh cục bộ",
    "động kinh toàn thể",
    "đột quy",
    "đột quỵ",
    "đột quỵ do thiếu máu não",
    "đột quỵ do xuất huyết não",
    "đột quỵ lacunary",
    "đột quỵ não",
    "đột quỵ thiếu máu",
    "đột quỵ xuất huyết",
    "đợt cấp hen suyễn",
    "đục thủy tinh thể",
    "ảo giác",
]